import * as M from './engine.mjs';
import {generateExercise} from './generator.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const num=x=>x===Infinity?'+\u221e':x===-Infinity?'\u2212\u221e':Number.isNaN(x)?'No definit':M.fmt(x);
const KEY='mates-batx-docent-v2';
const COURSES={all:'Tots els itineraris',sci1:'Matem\u00e0tiques I',sci2:'Matem\u00e0tiques II',soc1:'Aplicades CCSS I',soc2:'Aplicades CCSS II'};
let T=[],EX=[],PL={},Q=[],PRE=[],currentPreset=null,state,activeTool='calculus',lastResult=null,lastParams=null,worker=null,installPrompt=null,swRegistration=null,saveTimer;
const initial=()=>({schema:2,course:'all',theme:'light',favorites:[],notes:{},status:{},hours:{},plans:{},selected:[],exercises:[],lab:{}});
try{const data=localStorage.getItem(KEY);state=data?validateState(JSON.parse(data),false):initial();}catch{state=initial();}
function validateState(s,strict=true){
  if(!s||s.schema!==2||!Object.hasOwn(COURSES,s.course)||!['light','dark'].includes(s.theme))throw Error('C\u00f2pia incompatible: cal format de dades v2.');
  for(const map of ['notes','status','hours','plans','lab'])for(const k of Object.keys(s[map]||{}))if(['__proto__','constructor','prototype'].includes(k))throw Error('Clau de dades no admesa.');
  const a=initial();a.course=s.course;a.theme=s.theme;
  for(const k of ['favorites','selected']){if(!Array.isArray(s[k])||s[k].length>2000||s[k].some(v=>typeof v!=='string'||v.length>100))throw Error('Llista inv\u00e0lida: '+k);a[k]=[...new Set(s[k])];}
  for(const k of ['notes','status','hours','plans','lab']){if(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k])||Object.keys(s[k]).length>3000)throw Error('Dades inv\u00e0lides: '+k);a[k]={};}
  for(const[k,v]of Object.entries(s.notes)){if(typeof v!=='string'||v.length>30000)throw Error('Nota massa llarga.');a.notes[k]=v;}
  for(const[k,v]of Object.entries(s.status)){if(!['pending','planned','taught','review'].includes(v))throw Error('Estat inv\u00e0lid.');a.status[k]=v;}
  for(const[k,v]of Object.entries(s.hours)){if(!Number.isFinite(v)||v<0||v>200)throw Error('Sessions inv\u00e0lides.');a.hours[k]=v;}
  for(const[k,v]of Object.entries(s.plans)){if(!Array.isArray(v)||v.length!==3||v.some(r=>!Array.isArray(r)||r.length>100||r.some(id=>typeof id!=='string'||id.length>60)))throw Error('Pla inv\u00e0lid.');a.plans[k]=v;}
  for(const[k,v]of Object.entries(s.lab)){if(!v||typeof v!=='object'||Array.isArray(v))continue;a.lab[k]={};for(const[n,x]of Object.entries(v)){if(typeof x==='string'&&x.length<30000&&n.length<60&&!['__proto__','constructor','prototype'].includes(n))a.lab[k][n]=x;}}
  if(!Array.isArray(s.exercises)||s.exercises.length>1000)throw Error('Banc propi massa gran o inv\u00e0lid.');
  a.exercises=s.exercises.map(x=>{if(!x||typeof x.id!=='string'||typeof x.question!=='string'||x.question.length>20000||!Array.isArray(x.steps)||x.steps.some(t=>typeof t!=='string'||t.length>20000))throw Error('Exercici inv\u00e0lid.');return{id:x.id.slice(0,80),title:String(x.title||'Exercici propi').slice(0,200),question:x.question,steps:x.steps,origin:String(x.origin||'Exercici propi').slice(0,100),topic:String(x.topic||'algebra').slice(0,60)};});
  return a;
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#storage-warning').classList.add('hidden');}catch{$('#storage-warning').classList.remove('hidden');}}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(saveTimer);saveTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function dl(name,data,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const topic=id=>T.find(t=>t.id===id);
const tname=id=>topic(id)?.title||id;
const track=()=>state.course.startsWith('soc')?'soc':'sci';
const visibleTopics=()=>T.filter(t=>state.course==='all'||t.courses.includes(state.course));
const statusLabels={pending:'Pendent',planned:'Preparat',taught:'Treballat',review:'A revisar'};
const tag=(s,cl='')=>`<span class="tag ${cl}">${E(s)}</span>`;
const button=(label,act,id='',cl='secondary small')=>`<button class="${cl}" data-action="${act}" data-id="${E(id)}">${label}</button>`;
const sourceLink=(url,label,cls='')=>`<a class="${cls}" href="${E(url)}" target="_blank" rel="noopener noreferrer">${E(label)} \u2197</a>`;
function sourceRefs(t){return Object.entries(t.source).map(([tr,ps])=>ps.map(p=>sourceLink(`./docs/curriculum-${tr==='sci'?'matematiques':'socials'}.pdf#page=${p}`,`${tr==='sci'?'Mat.':'CCSS'} p. ${p}`)).join(' \u00b7 ')).join('<br>');}
function countTopic(id,tr=null,year=null){return EX.filter(e=>(!tr||e.track===tr)&&(!year||e.year===year)&&e.questions.some(q=>q.topics.includes(id))).length;}
function title(kicker,title,desc='',actions=''){return`<div class="page-head"><div><p class="eyebrow">${E(kicker)}</p><h1>${E(title)}</h1>${desc?`<p>${desc}</p>`:''}</div>${actions?`<div class="actions no-print">${actions}</div>`:''}</div>`;}
function steps(items){return`<ol class="sequence">${items.map(s=>`<li>${E(s)}</li>`).join('')}</ol>`;}
function metrics(items){return`<div class="metrics">${items.map(([n,l])=>`<div class="metric"><strong>${E(n)}</strong><span>${E(l)}</span></div>`).join('')}</div>`;}
function route(){
  ++job;clearTimeout(jobTimer);worker?.terminate();currentPreset=null;
  let full=location.hash.slice(1)||'home',[path,query='']=full.split('?'),[view,id]=path.split('/');
  $$('.sidebar nav a').forEach(a=>{let on=a.dataset.route===view;a.classList.toggle('active',on);on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});
  $('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');
  lastResult=null;lastParams=null;
  const fn={home:home,topics:()=>id?topicDetail(id):topics,lab:()=>lab(id||activeTool,new URLSearchParams(query)),exams:exams,comparison:comparison,planner:planner,workbook:workbook,settings:settings}[view]||home;
  let result=fn();if(typeof result==='function')result=result();$('#main').innerHTML=result;
  document.title=(view==='topics'&&id?tname(id):({home:'Inici',topics:'Temari',lab:'Laboratori',exams:'PAU',comparison:'Curr\u00edculum i PAU',planner:'Planificaci\u00f3',workbook:'Dossier',settings:'Dades i ajuda'}[view]||'Inici'))+' \u00b7 Mates Docent';
  if(view==='topics'&&!id)renderTopicGrid();if(view==='exams')renderExams();if(view==='comparison')renderComparison();
  if(view==='settings')refreshDiagnostics();
  window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});
}
function home(){const vt=visibleTopics(),done=vt.filter(t=>state.status[t.id]==='taught').length;
  return title('CURS 2026\u20132027 \u00b7 PREPARACI\u00d3 DOCENT','Matem\u00e0tiques, connectades.','Teoria, did\u00e0ctica i eines de c\u00e0lcul. Un espai per preparar classes amb criteri, no una plataforma per qualificar alumnes.')+
  `<div class="hero"><div><p class="eyebrow">DEL CONCEPTE A LA PISSARRA</p><h2>Entendre qu\u00e8 expliques.<br>Decidir com ho expliques.</h2><p>Cada tema connecta el sentit matem\u00e0tic, les f\u00f3rmules, els errors habituals i les evid\u00e8ncies que apareixen a les PAU.</p><div class="actions"><a href="#topics/derivative" class="button">Prepara una classe de derivades \u2192</a><a href="#lab" class="button secondary">Obre el laboratori</a></div></div><div class="hero-art"><p>CANVI \u2194 ACUMULACI\u00d3</p><div class="formula">f(x) \u2192 f\u2032(x) \u2192 f\u2032\u2032(x)</div><div class="formula">\u222b f(x) dx = F(x) + C</div><p>Concepte \u00b7 representaci\u00f3 \u00b7 justificaci\u00f3</p></div></div>`+
  metrics([[vt.length,'temes del teu itinerari'],[EX.length,'ex\u00e0mens oficials indexats'],[Q.length,'preguntes / opcions classificades'],[done+'/'+vt.length,'temes marcats com a treballats']])+
  `<div class="grid two"><section class="panel"><p class="eyebrow">LECTURA DEL CURR\u00cdCULUM</p><h2>El curr\u00edculum \u00e9s m\u00e9s ampli que l\u2019examen</h2><p class="muted">Les freq\u00fc\u00e8ncies descriuen la mostra 2024\u20132026. No prediuen les PAU ni justifiquen ometre un saber oficial.</p><div class="actions spaced"><a class="button subtle" href="#comparison">Consulta la comparativa</a></div></section><section class="panel"><p class="eyebrow">DADES TEVES, AL TEU NAVEGADOR</p><h2>Notes i planificaci\u00f3 sense compte</h2><p class="muted">Els canvis es desen en aquest navegador. Exporta una c\u00f2pia per canviar de dispositiu o abans de netejar-ne les dades.</p><div class="actions spaced">${button('Exporta una c\u00f2pia','export','','subtle')}</div></section></div>`+
  `<div class="section-head"><h2>Connexions per preparar la propera sessi\u00f3</h2><a href="#topics">Tot el temari \u2192</a></div><div class="grid">${['limits','derivative','integral','systems','bayes','inference'].map(id=>topicCard(topic(id))).join('')}</div>`+
  `<div class="notice">Base documental: els dos curr\u00edculums aportats (Decret 171/2022) i proves oficials ordin\u00e0ries i extraordin\u00e0ries de 2024, 2025 i 2026. Darrera revisi\u00f3 de fonts: 1 d\u2019octubre de 2026. Les sessions i els exemples propis s\u00f3n propostes docents.</div>`;
}
function topicCard(t){return`<article class="card"><div class="tags">${tag(t.block)}${state.favorites.includes(t.id)?tag('\u2605 Preferit','gold'):''}</div><h3><a href="#topics/${t.id}">${E(t.title)}</a></h3><p>${E(t.idea.split('. ')[0]+'.')}</p><div class="tags">${t.courses.map(c=>tag(COURSES[c],'neutral')).join('')}</div><div class="actions"><a class="button small secondary" href="#topics/${t.id}">Prepara el tema \u2192</a><span class="muted small">${t.id==='transversal'?'Transversal':countTopic(t.id,state.course==='all'?null:track())+' / '+(state.course==='all'?12:6)+' proves'}</span></div></article>`;}
function topics(){return title('BIBLIOTECA DOCENT','Temari i did\u00e0ctica','31 temes independents, amb f\u00f3rmules, seq\u00fc\u00e8ncia d\u2019explicaci\u00f3, exemples resolts i errors a anticipar.')+
  `<div class="toolbar no-print"><label class="search">Cerca un concepte<input id="topic-search" type="search" placeholder="Derivades, integrals, matrius, Bayes\u2026"></label><label>Bloc<select id="topic-block"><option value="all">Tots els blocs</option>${[...new Set(T.map(t=>t.block))].map(b=>`<option>${E(b)}</option>`).join('')}</select></label><label class="checkbox-line"><input id="topic-favorites" type="checkbox">Nom\u00e9s preferits</label></div><p id="topic-count" class="table-caption"></p><div id="topic-grid" class="grid"></div>`;}
function renderTopicGrid(){if(!$('#topic-grid'))return;let search=norm($('#topic-search').value),block=$('#topic-block').value,only=$('#topic-favorites').checked;let items=visibleTopics().filter(t=>(block==='all'||t.block===block)&&(!only||state.favorites.includes(t.id))&&norm(t.title+' '+t.idea+' '+t.formulas.map(f=>f.formula).join(' ')).includes(search));$('#topic-count').textContent=items.length+' temes';$('#topic-grid').innerHTML=items.length?items.map(topicCard).join(''):'<div class="empty">No hi ha temes amb aquests filtres.</div>';}
function topicDetail(id){const t=topic(id);if(!t)return'<div class="empty">Tema no trobat. <a href="#topics">Torna al temari</a></div>';let related=Q.filter(q=>q.topics.includes(id));
 return title(t.block,t.title,'<a href="#topics">\u2190 Tot el temari</a>',button(state.favorites.includes(id)?'\u2605 Preferit':'\u2606 Desa com a preferit','favorite',id))+
 `<div class="details-layout"><div><section class="panel"><p class="eyebrow">QU\u00c8 CAL COMPRENDRE</p><h2>La idea central</h2><p>${E(t.idea)}</p><div class="notice"><strong>Abans de comen\u00e7ar:</strong> ${E(t.prerequisites)}</div></section><section class="panel"><p class="eyebrow">FORMULARI AMB SIGNIFICAT</p><h2>F\u00f3rmules i condicions d\u2019\u00fas</h2>${t.formulas.map(f=>`<div class="formula-block"><div class="formula">${E(f.formula)}</div><p>${E(f.meaning)}</p></div>`).join('')}</section><section class="panel"><p class="eyebrow">GUI\u00d3 PER A LA PISSARRA</p><h2>Com explicar-ho, pas a pas</h2>${steps(t.sequence)}</section><section class="panel"><h2>Errors que conv\u00e9 anticipar</h2><ul class="error-list">${t.errors.map(s=>`<li>${E(s)}</li>`).join('')}</ul></section><section class="panel"><p class="eyebrow">EXEMPLES PROPIS</p><h2>Resolucions comentades</h2>${t.examples.map((e,i)=>`<details ${i===0?'open':''}><summary>${E(e.question)}</summary><div class="details-content">${steps(e.steps)}${button('Afegir exemple al dossier','add-example',id+':'+i)}</div></details>`).join('')}<div class="notice"><strong>Pregunta de sortida:</strong> ${E(t.exit)}</div></section><section class="panel"><h2>Connexi\u00f3 amb les PAU</h2><p class="muted">${related.length?'Preguntes on s\u2019ha identificat aquest tema. Obrir l\u2019original i el criteri permet verificar la interpretaci\u00f3.':'No s\u2019ha anotat cap pregunta amb aquesta etiqueta en la mostra. Aix\u00f2 no elimina el saber del curs.'}</p>${related.map(q=>questionRow(q)).join('')}</section></div>
 <aside class="side-panel sticky"><section class="panel"><p class="eyebrow">PREPARA I COMPROVA</p><h3>Laboratori del tema</h3><p>Les eines calculen dins un abast declarat. L\u2019explicaci\u00f3 i la justificaci\u00f3 continuen sent del docent.</p><div class="actions"><a class="button full-button" href="#lab/${t.tool}?f=${encodeURIComponent(t.expression)}">Obre l\u2019eina \u2192</a></div><label>Estat de preparaci\u00f3<select data-status="${id}">${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${(state.status[id]||'pending')===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Notes del docent<textarea class="note-field" data-note="${id}" placeholder="Exemples de classe, dificultats previstes, preguntes pendents\u2026">${E(state.notes[id]||'')}</textarea></label><div class="saved">Desament local autom\u00e0tic</div></section><section class="panel"><p class="eyebrow">TRA\u00c7ABILITAT</p><h3>Base curricular</h3><p>${sourceRefs(t)}</p><div class="notice">El t\u00edtol del tema i el gui\u00f3 s\u00f3n un desplegament did\u00e0ctic propi, no una transcripci\u00f3 literal del decret.</div><p><strong>Vincles d\u2019avaluaci\u00f3 proposats:</strong><br>CA ${t.criteria.join(', ')}.</p><p class="spaced">No hi ha una equival\u00e8ncia normativa \u00fanica entre un tema i un criteri.</p></section></aside></div>`;
}
function questionRow(q){let e=EX.find(e=>e.id===q.exam);return`<div class="question-row"><span class="q-label">${q.label}</span><div class="q-body"><small>${e.track==='sci'?'Matem\u00e0tiques':'CCSS'} \u00b7 ${e.year} \u00b7 ${e.session==='ord'?'juny':'setembre'} \u00b7 s\u00e8rie ${e.series} \u00b7 p. ${q.page}</small><p><strong>${E(q.title)}</strong></p><div class="tags">${q.topics.map(id=>`<a class="tag" href="#topics/${id}">${E(tname(id))}</a>`).join('')}</div>${q.note?`<div class="notice warning">${E(q.note)}</div>`:''}${presetLinks(q.id)}<div class="actions no-print">${sourceLink(e.url+'#page='+q.page,'Enunciat','button secondary small')}${sourceLink(e.correction,'Criteri oficial','button secondary small')}${button(state.selected.includes(q.id)?'\u2713 Al dossier':'\uff0b Dossier','select-question',q.id,'subtle small')}</div></div></div>`;}
function exams(){return title('FONTS OFICIALS \u00b7 MOSTRA 2024\u20132026','Banc de proves PAU','12 ex\u00e0mens i 64 registres de pregunta o opci\u00f3. Els resums s\u00f3n un \u00edndex propi; els enunciats i els criteris complets s\u2019obren al web oficial.')+
 `<div class="toolbar no-print"><label class="search">Cerca<input id="exam-search" placeholder="Capsa, continu\u00eftat, sistema, 4A\u2026" type="search"></label><label>Mat\u00e8ria<select id="exam-track"><option value="all">Totes dues</option><option value="sci" ${state.course.startsWith('sci')?'selected':''}>Matem\u00e0tiques II</option><option value="soc" ${state.course.startsWith('soc')?'selected':''}>CCSS II</option></select></label><label>Any<select id="exam-year"><option value="all">2024\u20132026</option><option value="2026">2026</option><option>2025</option><option>2024</option></select></label><label>Convocat\u00f2ria<select id="exam-session"><option value="all">Totes dues</option><option value="ord">Juny</option><option value="ext">Setembre</option></select></label></div><p id="exam-count" class="table-caption"></p><div id="exam-list"></div><div class="notice">S\u2019inclouen els tribunals ordinaris de juny i les convocat\u00f2ries extraordin\u00e0ries de setembre. Queden fora els tribunals especials i d\u2019incid\u00e8ncies. Els PDF externs necessiten connexi\u00f3; la classificaci\u00f3 i el temari queden disponibles offline.</div>`;}
function renderExams(){if(!$('#exam-list'))return;let s=norm($('#exam-search').value),tr=$('#exam-track').value,y=$('#exam-year').value,se=$('#exam-session').value;
 const es=EX.filter(e=>(tr==='all'||e.track===tr)&&(y==='all'||e.year===+y)&&(se==='all'||e.session===se)).map(e=>({...e,filtered:e.questions.filter(q=>norm(q.title+' '+q.label+' '+q.topics.map(tname).join(' ')).includes(s))})).filter(e=>e.filtered.length).sort((a,b)=>b.year-a.year||a.track.localeCompare(b.track)||a.session.localeCompare(b.session));
 $('#exam-count').textContent=es.length+' proves \u00b7 '+es.reduce((s,e)=>s+e.filtered.length,0)+' preguntes / opcions';
 $('#exam-list').innerHTML=es.length?es.map(e=>`<section class="panel"><div class="exam-head"><div><div class="tags">${tag(e.track==='sci'?'MATEM\u00c0TIQUES II':'APLICADES CCSS II')}${tag(e.year,'neutral')}</div><h2 class="spaced">${e.session==='ord'?'Convocat\u00f2ria ordin\u00e0ria \u00b7 juny':'Convocat\u00f2ria extraordin\u00e0ria \u00b7 setembre'}</h2><p>S\u00e8rie ${e.series} \u00b7 ${e.format} \u00b7 2,5 punts per exercici</p></div><div class="actions no-print">${sourceLink(e.url,'PDF oficial','button small secondary')}${sourceLink(e.correction,'Correccions','button small secondary')}</div></div><details ${s?'open':''}><summary>${e.filtered.length} preguntes / opcions classificades</summary><div class="details-content">${e.filtered.map(questionRow).join('')}</div></details></section>`).join(''):'<div class="empty">No hi ha proves amb aquests filtres.</div>';
}
function comparison(){return title('COMPARACI\u00d3 DOCUMENTADA','Curr\u00edculum \u00d7 PAU','Lectura dels sabers aportats i de les proves efectivament revisades. No \u00e9s una predicci\u00f3 ni una programaci\u00f3 oficial.')+
 `<div class="actions no-print">${sourceLink('./ANALISI_PAU_2024_2026.html','Informe complet de la comparativa','button secondary small')}</div>`+
 `<div class="toolbar no-print"><label>Mat\u00e8ria<select id="compare-track"><option value="sci" ${track()==='sci'?'selected':''}>Matem\u00e0tiques I i II</option><option value="soc" ${track()==='soc'?'selected':''}>Aplicades CCSS I i II</option></select></label><label>Abast<select id="compare-level"><option value="all">Tot el curr\u00edculum I + II</option><option value="2">Nom\u00e9s temes de II</option></select></label>${button('Exporta taula JSON','export-comparison')}</div><div class="notice"><strong>Com es compta:</strong> cada cel\u00b7la indica en quantes de les dues proves d\u2019aquell any apareix almenys una pregunta o opci\u00f3 etiquetada amb el tema. Les etiquetes se superposen. Una prova amb 4A i 4B nom\u00e9s compta una vegada per tema. No s\u00f3n percentatges de puntuaci\u00f3 ni de preguntes obligat\u00f2ries.</div><div id="compare-summary"></div><div id="compare-table"></div>
 <div class="grid two spaced"><section class="panel"><p class="eyebrow">CANVI DE FORMAT</p><h2>2024 no \u00e9s equivalent a 2025\u20132026</h2><p>El 2024 l\u2019estudiant triava quatre de sis q\u00fcestions. El 2025 i el 2026 resol els exercicis 1, 2 i 3 i tria A o B al quart. Una freq\u00fc\u00e8ncia de tema ofert no diu si era obligatori per a tothom.</p><p class="spaced">${sourceLink(EX[0].url+'#page=2','Examen Matem\u00e0tiques juny 2024')}<br>${sourceLink(EX[2].url+'#page=2','Examen Matem\u00e0tiques juny 2025')}<br>${sourceLink(EX[4].url+'#page=2','Examen Matem\u00e0tiques juny 2026')}</p></section><section class="panel"><p class="eyebrow">DECISI\u00d3 DOCENT</p><h2>Preparar sense retallar el curr\u00edculum</h2><p>La proposta \u00e9s reservar pr\u00e0ctica recurrent per a modelitzaci\u00f3, derivades, sistemes i probabilitat, i mantenir els altres sabers oficials encara que no apareguin en aquesta mostra. El raonament i la comunicaci\u00f3 es treballen durant tot el curs.</p><p class="spaced">Fonts de concreci\u00f3 2026:<br>${sourceLink('https://universitats.gencat.cat/ca/pau/materies-pau/matematiques/index.html','Matem\u00e0tiques')} \u00b7 ${sourceLink('https://universitats.gencat.cat/ca/pau/materies-pau/matematiques-aplicades-ciencies-socials/','CCSS')}</p></section></div>
 <section class="panel"><h2>Precisi\u00f3 en les interpretacions</h2><p><strong>Matem\u00e0tiques:</strong> normal i volums de revoluci\u00f3 figuren al curr\u00edculum aportat. No s\u2019han etiquetat com a presents en les sis proves revisades; un volum de tetraedre no \u00e9s un volum de revoluci\u00f3. La guia de Matem\u00e0tiques PAU 2026 enumera binomial al bloc probabil\u00edstic, per\u00f2 no normal.</p><p><strong>CCSS:</strong> les integrals figuren al curr\u00edculum de II, per\u00f2 no se n\u2019ha anotat pres\u00e8ncia en aquestes sis proves. La infer\u00e8ncia, en canvi, apareix de manera recurrent. A primer, el document ja inclou binomial i normal.</p><p><strong>Un detall de rigor:</strong> a CCSS juny 2026 s\u2019ha enlla\u00e7at la versi\u00f3 oficial v2. El criteri introdueix normalitat per relacionar una mitjana de temps amb el percentatge sota un llindar. L\u2019app conserva i assenyala aquesta hip\u00f2tesi.</p><p class="spaced">${sourceLink('./docs/curriculum-matematiques.pdf#page=18','Curr\u00edculum Matem\u00e0tiques, p. 18 i 21')}<br>${sourceLink('./docs/curriculum-socials.pdf#page=16','Curr\u00edculum CCSS, p. 16\u201319')}<br>${sourceLink(EX.find(e=>e.id==='soc-2026-ord').correction+'#page=6','Criteri CCSS juny 2026 v2, p. 6')}</p></section>`;
}
function comparisonData(){const tr=$('#compare-track')?.value||track(),level=$('#compare-level')?.value||'all';return T.filter(t=>t.courses.some(c=>c.startsWith(tr)&&(level==='all'||c.endsWith('2')))).map(t=>({id:t.id,tema:t.title,any2024:t.id==='transversal'?null:countTopic(t.id,tr,2024),any2025:t.id==='transversal'?null:countTopic(t.id,tr,2025),any2026:t.id==='transversal'?null:countTopic(t.id,tr,2026),total:t.id==='transversal'?null:countTopic(t.id,tr),curriculum:t.source[tr],track:tr}));}
function renderComparison(){if(!$('#compare-table'))return;const rows=comparisonData();$('#compare-summary').innerHTML=metrics([[6,'proves de la mat\u00e8ria'],[3,'anys revisats'],[rows.length,'temes en aquesta vista'],['2 / any','ordin\u00e0ria i extraordin\u00e0ria']]);$('#compare-table').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Tema / desplegament docent</th><th class="num">2024</th><th class="num">2025</th><th class="num">2026</th><th class="num">Total</th><th>Base curricular</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a href="#topics/${r.id}">${E(r.tema)}</a></td>${['any2024','any2025','any2026'].map(k=>`<td class="num">${r[k]===null?'\u2014':`<span class="${r[k]?'hit':'zero'}">${r[k]} / 2</span>`}</td>`).join('')}<td class="num">${r.total===null?'Transversal':r.total+' / 6'}</td><td>${sourceLink('./docs/curriculum-'+(r.track==='sci'?'matematiques':'socials')+'.pdf#page='+r.curriculum[0],'p. '+r.curriculum.join(', '))}</td></tr>`).join('')}</tbody></table></div><p class="table-caption">0 = no observat amb aquesta etiqueta a la mostra; no significa \u00abfora del curr\u00edculum\u00bb. Els temes instrumentals poden intervenir sense haver estat comptabilitzats com a demanda expl\u00edcita.</p>`;}
function planCourse(){return state.course==='all'?'sci2':state.course;}
function plannedHours(c,id){return state.hours[c+':'+id]??topic(id).sessions?.[c]??topic(id).hours;}
function planner(){const c=planCourse(),plan=state.plans[c]||PL[c],flat=plan.flat().filter(id=>topic(id)),total=flat.reduce((s,id)=>s+plannedHours(c,id),0);
 return title('SEQ\u00dcENCIACI\u00d3 EDITABLE','Planificaci\u00f3 del curs',`${E(COURSES[c])}. Proposta de treball per trimestres; les sessions no s\u00f3n una dotaci\u00f3 hor\u00e0ria oficial. Ajusta el pla al teu calendari real.`,button('Restaura la proposta','reset-plan',c))+
 `<div class="notice">${state.course==='all'?'S\u2019est\u00e0 mostrant Matem\u00e0tiques II. Canvia l\u2019itinerari a la cap\u00e7alera per veure un altre curs. ':''}El fil d\u2019an\u00e0lisi \u00e9s funcions \u2192 l\u00edmits \u2192 derivades \u2192 estudi \u2192 optimitzaci\u00f3 \u2192 integral. \u00c0lgebra lineal, geometria i probabilitat es poden reordenar. Comunicaci\u00f3, modelitzaci\u00f3 i gesti\u00f3 de l\u2019error es treballen en paral\u00b7lel.</div>`+
 metrics([[total,'sessions de contingut proposades'],[flat.length,'unitats del pla'],[flat.filter(id=>state.status[id]==='taught').length,'unitats marcades com a treballades'],[(c.endsWith('1')?128:112)-total,'sessions de reserva en aquest escenari']])+
 plan.map((ids,tri)=>`<section class="panel"><div class="section-head"><h2>Trimestre ${tri+1}</h2><span class="tag">Ordre i sessions editables</span></div>${ids.filter(id=>topic(id)).map((id,i)=>`<div class="plan-row"><small>${i+1}</small><p><a href="#topics/${id}">${E(tname(id))}</a></p><label><span class="sr-only">Sessions</span><input type="number" min="0" max="200" step="1" aria-label="Sessions ${E(tname(id))}" data-hours="${c}:${id}" value="${plannedHours(c,id)}"></label><select aria-label="Trimestre ${E(tname(id))}" data-move-topic="${id}" data-course="${c}" data-from="${tri}">${[0,1,2].map(v=>`<option value="${v}" ${v===tri?'selected':''}>Trimestre ${v+1}</option>`).join('')}</select><div class="actions no-print">${button('\u2191','plan-up',c+':'+tri+':'+id,'secondary small')}${button('\u2193','plan-down',c+':'+tri+':'+id,'secondary small')}</div></div>`).join('')}<p class="plan-total">Subtotal: ${ids.filter(id=>topic(id)).reduce((s,id)=>s+plannedHours(c,id),0)} sessions.</p></section>`).join('')+
 `<section class="panel"><h2>Notes de programaci\u00f3</h2><p class="hint">Escenari orientatiu, no calendari oficial: 32 setmanes de 4 sessions a primer (128) o 28 setmanes a segon (112). La reserva és la diferència respecte del contingut planificat. Ajusta el pla al calendari real; una reserva negativa indica sobrecàrrega en aquest escenari.</p><label>Distribuci\u00f3 real, instruments d\u2019avaluaci\u00f3 i adaptacions<textarea data-note="plan-${c}" placeholder="Afegeix el calendari del centre, sessions de retorn i ajustos\u2026">${E(state.notes['plan-'+c]||'')}</textarea></label><div class="saved">Desament local autom\u00e0tic</div></section>`;
}
function workbook(){let selected=Q.filter(q=>state.selected.includes(q.id));return title('BANC PROPI I SELECCI\u00d3 PAU','Dossier de preparaci\u00f3','Combina refer\u00e8ncies d\u2019ex\u00e0mens, exemples del temari i variants generades amb soluci\u00f3. Els exercicis generats s\u00f3n propis, no oficials.',button('Imprimeix el dossier','print'))+
 `<section class="panel no-print"><h2>Genera una variant resolta</h2><div class="toolbar"><label>Fam\u00edlia<select id="gen-family"><option value="quadratic">Equaci\u00f3 quadr\u00e0tica</option><option value="derivative">Derivada i tangent</option><option value="integral">Integral polin\u00f2mica</option><option value="system">Sistema lineal 2\u00d72</option><option value="binomial">Probabilitat binomial</option><option value="bayes">Probabilitat total i Bayes</option><option value="optimization">Optimitzaci\u00f3 quadr\u00e0tica</option><option value="confidence">Interval de confian\u00e7a</option></select></label><label>Llavor (reprodu\u00efble)<input id="gen-seed" type="number" value="2026" step="1"></label>${button('Genera i desa','generate','','') }</div><p class="hint">La mateixa fam\u00edlia i llavor produeixen el mateix exercici. La resoluci\u00f3 es construeix amb dades coherents i c\u00e0lcul local.</p><details><summary>Afegeix un exercici propi</summary><div class="details-content"><form id="custom-form"><label>T\u00edtol<input name="title" required maxlength="150"></label><label class="spaced">Enunciat<textarea name="question" required maxlength="20000"></textarea></label><label>Passos de soluci\u00f3 (un per l\u00ednia)<textarea name="steps" required maxlength="20000"></textarea></label><button type="submit">Desa l\u2019exercici propi</button></form></div></details></section>
 <section class="panel"><h2>Exercicis propis i exemples desats (${state.exercises.length})</h2>${state.exercises.length?state.exercises.map(e=>`<article class="workbook-item"><div class="tags">${tag(e.origin)}</div><h3 class="spaced">${E(e.title)}</h3><p>${E(e.question)}</p><details open><summary>Resoluci\u00f3 comentada</summary><div class="details-content">${steps(e.steps)}</div></details><div class="actions no-print">${button('Elimina del dossier','remove-exercise',e.id)}</div></article>`).join(''):'<div class="empty">Genera una variant o desa un exemple des del temari.</div>'}</section>
 <section class="panel"><h2>Refer\u00e8ncies PAU seleccionades (${selected.length})</h2><p class="muted">El dossier conserva t\u00edtol, proced\u00e8ncia i enlla\u00e7os. No reprodueix els PDF ni genera una correcci\u00f3 autom\u00e0tica de l\u2019examen complet.</p>${selected.length?selected.map(questionRow).join(''):'<div class="empty">Selecciona preguntes al banc PAU o dins cada tema.</div>'}</section>`;}
function settings(){return title('DADES \u00b7 DOCUMENTACI\u00d3 \u00b7 INSTAL\u00b7LACI\u00d3','Una app transparent','Qu\u00e8 funciona localment, quines fonts s\u2019han revisat i quins l\u00edmits s\u2019han de tenir en compte.')+
 `<div class="grid two"><section class="panel"><h2>C\u00f2pies de seguretat</h2><p>Notes, preferits, pla, dossier i darrers par\u00e0metres es desen nom\u00e9s en aquest navegador i origen web. No hi ha sincronitzaci\u00f3 entre dispositius.</p><div class="actions spaced">${button('Exporta totes les dades','export','','')}${button('Esborra dades locals','reset-data','','secondary')}</div><label class="backup-label spaced">Importa una c\u00f2pia JSON (substitueix les dades locals)<input id="import-file" type="file" accept="application/json,.json"></label><p class="hint">Abans d\u2019importar, es demana confirmaci\u00f3. M\u00e0xim 2 MB. El format es valida i cap text importat s\u2019executa com a codi.</p></section><section class="panel"><h2>Estat de l\u2019aplicaci\u00f3</h2><div id="diagnostics" class="notice">Comprovant\u2026</div><div class="actions">${button('Comprova actualitzacions','check-update','','secondary')}${button('Ajuda per instal\u00b7lar','install-help','','subtle')}</div><p class="hint">El primer acc\u00e9s ha de completar la c\u00e0rrega. El navegador pot alliberar mem\u00f2ria cau; les c\u00f2pies JSON s\u00f3n la protecci\u00f3 de les teves dades.</p></section></div>
 <section class="panel"><h2>Abast real del laboratori</h2><p><strong>Expressions:</strong> x, nombres, + - * / ^, par\u00e8ntesis, sin, cos, tan, asin, acos, atan, exp, ln/log (natural), sqrt i abs. Angles en radians. Admet 2x i 2(x+1). Una sola variable. Els trams es treballen separadament; no s\u2019admet codi ni condicions dins una expressi\u00f3.</p><p><strong>Simb\u00f2lic:</strong> derivades elementals i primitives restringides a les fam\u00edlies declarades. El domini original sempre preval sobre el d\u2019una expressi\u00f3 simplificada. No \u00e9s un sistema d\u2019\u00e0lgebra universal ni interpreta fotografies o enunciats lliures.</p><p><strong>Num\u00e8ric:</strong> arrels, quadratura, Gauss, probabilitats i intervals treballen en coma flotant. La gr\u00e0fica \u00e9s un mostreig, no una prova de continu\u00eftat. No s\u2019admeten integrals impr\u00f2pies. L\u00edmits certificats per estructura nom\u00e9s en funcions racionals admeses; altres expressions ofereixen una taula explorat\u00f2ria.</p><p><strong>Estad\u00edstica:</strong> normal acumulada aproximada, binomial per recurr\u00e8ncia estable, intervals normals amb hip\u00f2tesis i validacions. No inclou t de Student ni infer\u00e8ncia bayesiana. El producte de matrius no \u00e9s entrada a entrada; els sistemes es classifiquen amb rang.</p></section>
 <section class="panel"><h2>Fonts i versions</h2><ul class="source-list"><li>${sourceLink('./docs/curriculum-matematiques.pdf','Matem\u00e0tiques I i II \u00b7 document aportat del Decret 171/2022')}</li><li>${sourceLink('./docs/curriculum-socials.pdf','Matem\u00e0tiques Aplicades a les Ci\u00e8ncies Socials I i II \u00b7 document aportat')}</li><li>${sourceLink('https://universitats.gencat.cat/ca/pau/models-examen-anys-anteriors/matematiques/','Arxiu oficial de Matem\u00e0tiques 2024\u20132025')}</li><li>${sourceLink('https://universitats.gencat.cat/ca/pau/models-examen-anys-anteriors/matematiques-aplicades-cc/','Arxiu oficial de CCSS 2024\u20132025')}</li><li>${sourceLink('https://universitats.gencat.cat/ca/pau/examens-criteris-correccions/dia2/matematiques/','Ex\u00e0mens i criteris oficials de Matem\u00e0tiques 2026')}</li><li>${sourceLink('https://universitats.gencat.cat/ca/pau/examens-criteris-correccions/dia3/matematiques-aplicades-cc/','Ex\u00e0mens i criteris oficials de CCSS 2026')}</li><li>${sourceLink('https://developer.mozilla.org/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable','Documentaci\u00f3 d\u2019instal\u00b7laci\u00f3 PWA (MDN)')}</li><li>${sourceLink('https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site','Publicaci\u00f3 a GitHub Pages')}</li></ul><p class="hint">Revisi\u00f3: 2026-10-01. Inclou enlla\u00e7os v2 quan la font oficial els publica. La classificaci\u00f3, les propostes did\u00e0ctiques i els exemples propis no s\u00f3n documents oficials del Departament ni del tribunal.</p></section>
 <section class="panel"><h2>Publicaci\u00f3 i manteniment</h2><p>Descomprimeix el ZIP i puja tots els fitxers a l\u2019arrel del repositori. A GitHub: Settings \u2192 Pages \u2192 Deploy from a branch \u2192 main \u2192 /(root). L\u2019app utilitza rutes relatives i no necessita compilaci\u00f3, npm ni claus API.</p><p>Quan substitueixis una versi\u00f3 antiga, conserva el nom i la ubicaci\u00f3 del repositori per mantenir l\u2019origen del navegador. Exporta les notes abans de canviar d\u2019adre\u00e7a o netejar dades. El service worker nou elimina les mem\u00f2ries cau antigues conegudes d\u2019aquesta app, no les d\u2019altres llocs.</p><p class="spaced">Documentaci\u00f3 t\u00e8cnica i proves dins el ZIP: README.md, tests/engine.test.mjs i QA.md. No s\u2019ha publicat autom\u00e0ticament al teu compte de GitHub.</p></section>`;}

const TOOLS={
 calculus:{title:'Funcions, derivades i integrals',hint:'Derivaci\u00f3 simb\u00f2lica elemental, tangent, punts estacionaris quan \u00e9s possible i integral definida num\u00e8rica. La gr\u00e0fica ajuda a explicar, no certifica el domini.',defaults:{f:'x^3-3*x',a:'1',lo:'-1',hi:'1',area:'signed'},fields:[['f','Expressi\u00f3 f(x)','text'],['a','Punt de tangent x = a','number'],['lo','Integral: extrem inferior','number'],['hi','Integral: extrem superior','number'],['area','Tipus d\u2019integral','select',[['signed','Integral amb signe'],['geometric','\u00c0rea geom\u00e8trica: integral de |f|']]]]},
 equation:{title:'Equacions',hint:'Escriu f(x) per resoldre f(x)=0. Mode polinomi: arrels reals fins a grau 12 i complexes de quadr\u00e0tiques. Mode bisecci\u00f3: una arrel en un interval continu amb canvi de signe.',defaults:{f:'x^2-x-2',mode:'polynomial',lo:'0',hi:'2'},fields:[['f','Membre esquerre f(x)','text'],['mode','M\u00e8tode','select',[['polynomial','Polinomi (grau \u2264 12)'],['bisect','Bisecci\u00f3 en un interval']]],['lo','Bisecci\u00f3: extrem esquerre','number'],['hi','Bisecci\u00f3: extrem dret','number']]},
 limit:{title:'L\u00edmits i continu\u00eftat',hint:'An\u00e0lisi per ordres d\u2019anul\u00b7laci\u00f3 en expressions racionals. Per a altres funcions, nom\u00e9s exploraci\u00f3 num\u00e8rica: la taula no demostra el l\u00edmit.',defaults:{f:'(x^2-1)/(x-1)',point:'1'},fields:[['f','Funci\u00f3 f(x)','text'],['point','Punt (nombre, inf o -inf)','text']]},
 system:{title:'Sistemes lineals: Gauss',hint:'Escriu la matriu ampliada [A|b]. Una equaci\u00f3 per fila; coeficients separats per espais. La darrera columna \u00e9s el terme independent. M\u00e0xim 6 equacions i 6 inc\u00f2gnites.',defaults:{A:'1 1 1 6\n2 -1 1 3\n1 2 -1 2'},fields:[['A','Matriu ampliada','textarea']]},
 parameters:{title:'Sistemes amb par\u00e0metre',hint:'Matriu ampliada 2\u00d73 o 3\u00d74. Coeficients polin\u00f2mics en m, sense espais interns: m+1. Detecta zeros del determinant i classifica aquests casos amb Gauss num\u00e8ric.',defaults:{A:'1 1 2\n1 m m+1',m:'1'},fields:[['A','Matriu ampliada amb m','textarea'],['m','Valor concret per comprovar','number']]},
 matrix:{title:'Operacions amb matrius',hint:'Files separades per salts de l\u00ednia o punt i coma; nombres separats per espais. El producte \u00e9s fila per columna. La suma i el producte necessiten B.',defaults:{A:'1 2\n3 4',B:'2 0\n1 2',operation:'multiply'},fields:[['operation','Operaci\u00f3','select',[['multiply','A \u00b7 B'],['add','A + B'],['inverse','Inversa d\u2019A'],['determinant','Determinant d\u2019A'],['transpose','Transposada d\u2019A']]],['A','Matriu A','textarea'],['B','Matriu B (nom\u00e9s suma / producte)','textarea']]},
 bayes:{title:'Probabilitat total i Bayes',hint:'Defineix una partici\u00f3 d\u2019esdeveniments A\u2081, A\u2082, \u2026 i les probabilitats condicionades de l\u2019evid\u00e8ncia E. Introdueix probabilitats entre 0 i 1, no percentatges.',defaults:{prior:'0.6 0.4',likelihood:'0.1 0.3'},fields:[['prior','P(Ai), separades per espais; suma = 1','text'],['likelihood','P(E | Ai), en el mateix ordre','text']]},
 binomial:{title:'Distribuci\u00f3 binomial',hint:'Calcula P(a \u2264 X \u2264 b) amb X~B(n,p), per recurr\u00e8ncia estable. Extrems enters i inclusius. Per a P(X=k), posa el mateix k a tots dos extrems.',defaults:{n:'20',p:'0.4',lo:'5',hi:'10',correction:'yes'},fields:[['n','Nombre d\u2019assajos n (1..10000)','number'],['p','Probabilitat d\u2019\u00e8xit p','number'],['lo','a: primer valor incl\u00f2s','number'],['hi','b: darrer valor incl\u00f2s','number'],['correction','Comparaci\u00f3 normal','select',[['yes','Amb correcci\u00f3 de continu\u00eftat'],['no','Sense correcci\u00f3 (si ho demana l\u2019enunciat)']]]]},
 normal:{title:'Distribuci\u00f3 normal',hint:'N(\u03bc,\u03c3): el segon par\u00e0metre d\u2019aquesta eina \u00e9s la desviaci\u00f3, no la vari\u00e0ncia. La funci\u00f3 acumulada utilitza una aproximaci\u00f3 num\u00e8rica.',defaults:{mu:'0',sigma:'1',lo:'-1.96',hi:'1.96'},fields:[['mu','Mitjana \u03bc','number'],['sigma','Desviaci\u00f3 \u03c3 > 0','number'],['lo','Extrem inferior (admet -inf)','text'],['hi','Extrem superior (admet inf)','text']]},
 confidence:{title:'Intervals de confian\u00e7a',hint:'Intervals normals per a mitjana o proporci\u00f3. La mostra ha de ser aleat\u00f2ria i independent. No inclou t de Student; rebutja Wald amb menys de 10 \u00e8xits o fracassos.',defaults:{kind:'known',center:'50',spread:'10',n:'100',level:'0.95'},fields:[['kind','Par\u00e0metre i hip\u00f2tesis','select',[['known','Mitjana: sigma poblacional coneguda'],['sample','Mitjana: sigma desconeguda, n \u2265 30'],['proportion','Proporci\u00f3: interval normal de Wald']]],['center','Mitjana o proporci\u00f3 mostral','number'],['spread','Sigma o s (ignorat en proporci\u00f3)','number'],['n','Mida mostral n','number'],['level','Nivell de confian\u00e7a (p. ex. 0.95)','number']]},
 statistics:{title:'Estad\u00edstica i regressi\u00f3',hint:'Una variable: llista de dades. Dues variables: un parell x y per fila. Retorna les desviacions poblacional i mostral diferenciades. No fa ajust quadr\u00e0tic autom\u00e0tic.',defaults:{mode:'paired',data:'1 2\n2 3\n3 5\n4 4\n5 6'},fields:[['mode','Tipus de dades','select',[['paired','Parells (x,y): regressi\u00f3 lineal'],['single','Una variable: resum descriptiu']]],['data','Dades (fins a 2000 observacions)','textarea']]},
 geometry:{title:'Vectors i geometria de l\u2019espai',hint:'Punts P, Q, R amb tres coordenades separades per espais. Per al pla, escriu A B C D en Ax+By+Cz+D=0. Per treballar en el pla, usa z=0.',defaults:{P:'0 0 1',Q:'2 0 1',R:'0 3 1',plane:'0 0 1 0'},fields:[['P','P: x y z','text'],['Q','Q: x y z','text'],['R','R: x y z','text'],['plane','Pla: A B C D','text']]},
 finance:{title:'Model financer escolar',hint:'Model ideal de quota constant, pagament a final de per\u00edode, sense comissions ni impostos. El tipus r \u00e9s per per\u00edode: un 1% mensual s\u2019escriu 0.01. No \u00e9s assessorament financer.',defaults:{capital:'10000',rate:'0.005',n:'24'},fields:[['capital','Capital inicial','number'],['rate','Tipus decimal per per\u00edode','number'],['n','Nombre de per\u00edodes','number']]}
};
function field(f,values){const[k,label,type,options]=f;let val=values[k]??'';return `<label>${E(label)}${type==='select'?`<select name="${k}">${options.map(([v,l])=>`<option value="${v}" ${v===val?'selected':''}>${E(l)}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${k}" spellcheck="false" rows="5" maxlength="30000" required>${E(val)}</textarea>`:`<input name="${k}" type="${type}" ${type==='number'?'step="any"':''} value="${E(val)}" maxlength="400" spellcheck="false" required>`}</label>`;}
function lab(tool,params){if(!TOOLS[tool])tool='calculus';activeTool=tool;currentPreset=PRE.find(p=>p.id===params.get('preset')&&p.tool===tool)||null;const t=TOOLS[tool],v={...t.defaults,...state.lab[tool],...(currentPreset?.params||{})};if(params.has('f')&&t.fields.some(f=>f[0]==='f'))v.f=params.get('f');return title('C\u00c0LCUL LOCAL \u00b7 EXPLICACI\u00d3 DOCENT','Laboratori matem\u00e0tic','Eines independents, sense API ni intel\u00b7lig\u00e8ncia artificial externa. Resultats i restriccions visibles.',button('Mode projecci\u00f3','project'))+presetNotice()+
 `<div class="toolbar no-print"><label class="search">Eina<select id="tool-select">${Object.entries(TOOLS).map(([k,v])=>`<option value="${k}" ${k===tool?'selected':''}>${E(v.title)}</option>`).join('')}</select></label></div><div class="lab-layout"><section class="panel tool-form no-print"><p class="eyebrow">ENTRADA DE DADES</p><h2>${E(t.title)}</h2><p class="hint">${E(t.hint)}</p><form id="tool-form" data-tool="${tool}">${t.fields.map(f=>field(f,v)).join('')}<button type="submit" id="solve-button" class="full-button">Calcula i explica \u2192</button><div class="actions">${button('Carrega exemple','tool-defaults',tool,'subtle small')}</div><p class="hint">Ctrl + Retorn per calcular. S\u2019admet punt o coma decimal en camps de text; els vectors i les matrius se separen amb espais. Radians a les funcions trigonom\u00e8triques.</p></form></section><section id="lab-output" class="result" aria-live="polite"><div class="panel empty"><span class="empty-symbol" aria-hidden="true">\u0192</span><h2>Un c\u00e0lcul amb context</h2><p>Introdueix les dades i prem \u00abCalcula i explica\u00bb. Veur\u00e0s els passos disponibles, les hip\u00f2tesis i les comprovacions.</p><p class="hint">No interpreta enunciats lliures ni fotografies. Els c\u00e0lculs extensos es processen en un fil separat per no bloquejar l\u2019app.</p></div></section></div>`;}
function resultPanel(title,body,cls=''){return`<section class="panel ${cls}"><h2>${title}</h2>${body}</section>`;}
function mtable(rows,headers=null){return`<div class="table-scroll"><table>${headers?`<thead><tr>${headers.map(h=>`<th>${E(h)}</th>`).join('')}</tr></thead>`:''}<tbody>${rows.map(r=>`<tr>${r.map(x=>`<td class="num">${E(typeof x==='number'?num(x):x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function displayMatrix(m){return mtable(m);}
function math(ast){return'<div class="math-output">'+M.mathML(ast)+'</div>';}
function problem(msg){return `<div class="notice warning">${E(msg)}</div>`;}
function systemResult(r,showSteps=true){return resultPanel(`Classificaci\u00f3: ${E(r.kind)}`,`<p>${{SCD:'Sistema compatible determinat: una \u00fanica soluci\u00f3.',SCI:'Sistema compatible indeterminat: infinites solucions.',SI:'Sistema incompatible: cap soluci\u00f3.'}[r.kind]}</p>${metrics([[r.rank,'rang d\u2019A'],[r.augRank,'rang de [A|b]']])}<h3>Matriu redu\u00efda</h3>${displayMatrix(r.rref)}${r.kind==='SI'?'':`<h3 class="spaced">${r.kind==='SCI'?'Soluci\u00f3 particular':'Soluci\u00f3'}</h3><div class="formula">(${r.particular.map(num).join(', ')})</div>${r.basis.length?`<p>Afegir combinacions lineals dels vectors seg\u00fcents, amb par\u00e0metres reals lliures:</p>${displayMatrix(r.basis)}`:''}`}<p class="hint">Eliminaci\u00f3 en coma flotant amb pivotatge. Tol. de treball: ${num(r.tolerance)}. Verifica sistemes mal condicionats a m\u00e0.</p>${showSteps?`<details><summary>Veure operacions de Gauss (${r.steps.length})</summary><div class="details-content">${r.steps.map((s,i)=>`<p class="spaced"><strong>${i+1}. ${E(s.label)}</strong></p>${displayMatrix(s.matrix)}`).join('')}</div></details>`:''}`);}
function calculusResult(r,p){let html=resultPanel('Derivades simb\u00f2liques',`<p class="result-label">Funci\u00f3 original f(x)</p>${math(r.ast)}<p class="result-label">Primera derivada f\u2032(x)</p>${math(r.d)}<p class="result-label">Segona derivada f\u2032\u2032(x)</p>${math(r.dd)}<details><summary>Regles utilitzades</summary><div class="details-content">${steps(r.trace.length?r.trace:['La derivada d\u2019una constant \u00e9s zero.'])}</div></details><div class="notice">Les expressions s\u00f3n v\u00e0lides on la funci\u00f3 original \u00e9s definida i derivable. Una simplificaci\u00f3 no restitueix punts exclosos del domini. Comprova especialment abs, radicals i pot\u00e8ncies no enteres.</div>`);
 html+=resultPanel('Representaci\u00f3 i exploraci\u00f3',graphHTML(r,p));
 html+=resultPanel('Recta tangent i recta normal',r.point?`<p>Punt de contacte (${num(r.point.a)}, ${num(r.point.y)}). Pendent f\u2032(a) = ${num(r.point.slope)}.</p><div class="formula">y \u2212 (${num(r.point.y)}) = ${num(r.point.slope)} \u00b7 [x \u2212 (${num(r.point.a)})]</div><p class="spaced">${r.point.normal===null?'La normal \u00e9s vertical: x = '+num(r.point.a):'Normal: y \u2212 ('+num(r.point.y)+') = '+num(r.point.normal)+' \u00b7 [x \u2212 ('+num(r.point.a)+')]'}</p><p class="hint">El programa avalua la derivada formal. No prova la derivabilitat en punts singulars.</p>`:problem(r.pointError));
 html+=resultPanel('Punts estacionaris',r.critical===null?problem('Aquesta funci\u00f3 no admet cerca autom\u00e0tica de totes les arrels de f\u2032 amb l\u2019algorisme implementat. Usa el solucionador per intervals i el raonament anal\u00edtic.'):r.critical.length?mtable(r.critical.map(v=>[v.x,v.y,v.dd,Math.abs(v.dd)<1e-7?'Criteri inconcloent: estudia el signe':v.dd>0?'M\u00ednim local si hi ha regularitat':'M\u00e0xim local si hi ha regularitat']),['x (aprox.)','f(x)','f\u2032\u2032(x)','Interpretaci\u00f3'])+'<p class="hint">Candidats num\u00e8rics f\u2032=0; no inclou extrems del domini ni punts no derivables. La llista no \u00e9s una prova d\u2019exhaustivitat en casos mal condicionats.</p>':'<p>No s\u2019han trobat zeros a\u00efllats de la primera derivada. Per a funcions constants, tots els punts s\u00f3n estacionaris.</p>');
 html+=resultPanel('Primitiva i integral definida',`${r.primitive?`<p>Una primitiva F(x), a la qual cal afegir C:</p>${math(r.primitive)}${steps(r.primTrace)}`:problem(r.primitiveError)}${r.integral?`<h3 class="spaced">${p.area==='geometric'?'\u00c0rea geom\u00e8trica':'Integral amb signe'} entre ${E(p.lo)} i ${E(p.hi)}</h3><div class="formula">\u2248 ${num(r.integral.value)}</div><p>${E(r.integral.method)}.</p>${r.integral.converged===false?problem('No s\u2019ha assolit el criteri de converg\u00e8ncia amb el l\u00edmit de subdivisions. No acceptis el resultat sense comprovar-lo.'):''}${steps(r.integral.steps)}${r.integral.antiderivativeDifference!==undefined?`<p><strong>Comprovaci\u00f3 amb la primitiva:</strong> F(b)\u2212F(a) \u2248 ${num(r.integral.antiderivativeDifference)}.</p>`:''}`:problem(r.integralError)}<p class="hint">No calcula integrals impr\u00f2pies. L\u2019estimaci\u00f3 d\u2019error no \u00e9s una cota matem\u00e0tica rigorosa.</p>`);return html;
}
function renderResult(r,p){let html='';
 if(r.tool==='calculus')html=calculusResult(r,p);
 if(r.tool==='equation')html=resultPanel('Resoluci\u00f3 de f(x) = 0',`${steps(r.steps)}${r.mode==='bisect'?metrics([[num(r.root),'arrel aproximada'],[num(r.residual),'residu |f(x)|']]):`${r.roots.length?mtable(r.roots.map(x=>[x.fraction||'\u2248 '+num(x.x),x.residual]),['Arrel','Residu |f(x)|']):`<p>${r.identity?'Tots els reals del domini original.':r.complex?'No hi ha arrels reals.':'No s\u2019han trobat arrels reals amb aquest m\u00e8tode.'}</p>`}${r.complex?`<div class="formula">x = ${num(r.complex.real)} \u00b1 ${num(r.complex.imaginary)} i</div>`:''}` }<div class="notice">Comprova cada resultat per substituci\u00f3 i conserva les restriccions originals. Les fraccions mostrades reconstrueixen valors num\u00e8rics propers; no s\u00f3n aritm\u00e8tica exacta de precisi\u00f3 arbitr\u00e0ria.</div>`);
 if(r.tool==='limit'){let finite=Number.isFinite(r.point);html=resultPanel('An\u00e0lisi del l\u00edmit',r.result?`${metrics(finite?[[num(r.result.left),'l\u00edmit per l\u2019esquerra'],[num(r.result.right),'l\u00edmit per la dreta']]:[[num(r.result.right),'l\u00edmit a '+num(r.point)]])}<p>${finite?(r.result.left===r.result.right?Number.isFinite(r.result.left)?'Els dos l\u00edmits laterals finits coincideixen.':'Els laterals coincideixen en el sentit de l\u2019infinit indicat; no hi ha l\u00edmit finit.':'Els laterals no coincideixen: no existeix el l\u00edmit bilateral.'):'Comparaci\u00f3 del comportament dominant.'}</p>${steps(r.result.steps)}${r.result.warning?problem(r.result.warning):''}`:problem(r.error));html+=resultPanel('Taula explorat\u00f2ria',mtable(r.table.map(t=>finite?[t.leftX,t.left,t.rightX,t.right]:[t.leftX,t.left]),finite?['x < a','f(x)','x > a','f(x)']:['x','f(x)'])+'<p class="hint">Una taula finita no prova un l\u00edmit. La continu\u00eftat exigeix, a m\u00e9s, que f(a) estigui definida i coincideixi amb el l\u00edmit finit.</p>');}
 if(r.tool==='system')html=systemResult(r);
 if(r.tool==='parameters')html=resultPanel('Discussi\u00f3 del sistema',`<p>Determinant d\u2019A(m):</p><div class="formula">${E(r.det)}</div><p class="spaced">${r.exceptions===null?'Determinant nul per a tot m.':r.exceptions.length?'Valors excepcionals aproximats: '+r.exceptions.map(num).join(', '):'No s\u2019han trobat zeros reals del determinant.'}</p>${problem(r.warning)}`)+r.special.map(s=>resultPanel('Cas m \u2248 '+num(s.m),systemResult(s,false))).join('')+resultPanel('Comprovaci\u00f3 a m = '+num(r.at.m),systemResult(r.at));
 if(r.tool==='matrix')html=resultPanel('Resultat de l\u2019operaci\u00f3',Array.isArray(r.result)?displayMatrix(r.result):`<div class="formula">${num(r.result)}</div>`)+resultPanel('Procediment i comprovaci\u00f3',steps(r.steps));
 if(r.tool==='bayes')html=resultPanel('Probabilitat total',`<p>P(E) = \u03a3 P(Ai) P(E|Ai)</p><div class="formula">P(E) \u2248 ${num(r.evidence)}</div>`)+resultPanel('Probabilitats conjuntes i posteriors',mtable(r.posterior.map((v,i)=>['A'+(i+1),r.joint[i],v]),['Origen','P(Ai \u2229 E)','P(Ai | E)'])+steps(['Multiplicar cada probabilitat inicial per la seva versemblan\u00e7a.','Sumar les probabilitats conjuntes per obtenir P(E).','Dividir cada conjunta per P(E). Les posteriors sumen 1.']));
 if(r.tool==='binomial')html=resultPanel('Probabilitat binomial',metrics([[num(r.probability),'P('+r.lo+' \u2264 X \u2264 '+r.hi+')'],[num(r.mean),'esperan\u00e7a n\u00b7p'],[num(r.sd),'desviaci\u00f3 \u221a(np(1\u2212p))']])+steps(['Model: X~B('+r.n+', '+r.p+').','P(X=k)=C(n,k)p^k(1-p)^(n-k).','Sumar els termes des de k='+r.lo+' fins a k='+r.hi+', inclusivament. La implementaci\u00f3 usa recurr\u00e8ncies al voltant de la moda per evitar factorials enormes.']))+(r.approx?resultPanel('Aproximaci\u00f3 normal, per comparar',`<div class="formula">\u2248 ${num(r.approx.probability)}</div><p>${r.continuity?'Amb':'Sense'} correcci\u00f3 de continu\u00eftat. Extrems tipificats: ${num(r.approx.zl)}, ${num(r.approx.zr)}.</p>${r.approx.reliable?'':problem('np o n(1-p) \u00e9s inferior a 10: l\u2019aproximaci\u00f3 normal pot ser poc fiable.')}<p class="hint">Llegeix l\u2019enunciat: CCSS juny 2026 demana expl\u00edcitament no aplicar correcci\u00f3 de continu\u00eftat.</p>`):'');
 if(r.tool==='normal')html=resultPanel('Tipificaci\u00f3 i probabilitat',metrics([[num(r.zl),'z inferior'],[num(r.zr),'z superior'],[num(r.probability),'P(a \u2264 X \u2264 b)']])+steps(['Tipificar cada extrem: z=(x-\u03bc)/\u03c3.','Restar les probabilitats acumulades: \u03a6(z superior) - \u03a6(z inferior).','En una variable cont\u00ednua, P(X=x)=0: incloure o excloure un extrem no canvia aquesta probabilitat.'])+'<p class="hint">CDF aproximada: precisi\u00f3 absoluta de l\u2019ordre de 10\u207b\u2077 en el rang ordinari. A cues extremes, la resta pot arrodonir-se a zero.</p>');
 if(r.tool==='confidence')html=resultPanel('Interval de confian\u00e7a normal',`<div class="formula">[${num(r.lo)}, ${num(r.hi)}]</div>${metrics([[num(r.z),'quantil z'],[num(r.se),'error est\u00e0ndard'],[num(r.margin),'marge d\u2019error']])}${steps(['Calcular l\u2019error est\u00e0ndard corresponent.','Trobar el quantil del nivell de confian\u00e7a bilateral.','Marge = z \u00b7 error est\u00e0ndard; interval = estimaci\u00f3 \u00b1 marge.'])}${problem(r.warning)}`);
 if(r.tool==='statistics')html=resultPanel('Resum de les dades',metrics([[r.n,'observacions'],[num(r.mean),'mitjana de x'],[num(r.median),'mediana de x']])+mtable([['M\u00ednim',r.min],['M\u00e0xim',r.max],['Desviaci\u00f3 descriptiva (divisor n)',r.sdPopulation],['Desviaci\u00f3 mostral (divisor n-1)',r.sdSample]],['Mesura','Valor']))+(r.r!==undefined?resultPanel('Regressi\u00f3 lineal de y sobre x',`<div class="formula">\u0177 = ${num(r.slope)} x + (${num(r.intercept)})</div>${metrics([[num(r.r),'correlaci\u00f3 de Pearson r'],[num(r.r*r),'R\u00b2'],[num(r.meanY),'mitjana de y']])}${problem('Correlaci\u00f3 no implica causalitat. Revisa el n\u00favol de punts i evita extrapolar fora del rang observat; r no detecta totes les relacions no lineals.')}`):'');
 if(r.tool==='geometry')html=resultPanel('Vectors, productes i \u00e0rea',mtable([['PQ',r.u.map(num).join(', ')],['PR',r.v.map(num).join(', ')],['PQ \u00d7 PR',r.cross.map(num).join(', ')],['\u00c0rea triangle',r.area],['Angle QPR (graus)',r.angle??'No definit']],['Magnitud','Resultat'])+steps(['Formar PQ=Q-P i PR=R-P.','El m\u00f2dul del producte vectorial \u00e9s l\u2019\u00e0rea del paral\u00b7lelogram; dividir-lo per 2 per al triangle.']))+resultPanel('Plans i projecci\u00f3',`<p>Dist\u00e0ncia de P al pla d\u2019entrada: <strong>${num(r.distance)}</strong>.</p><p>Peu de la perpendicular de P al pla: (${r.projection.map(num).join(', ')}).</p><p class="spaced">${r.planeThrough?'Pla que cont\u00e9 P,Q,R: '+r.planeThrough.slice(0,3).map((x,i)=>num(x)+['x','y','z'][i]).join(' + ')+' + ('+num(r.planeThrough[3])+')=0.':'P, Q i R s\u00f3n alineats o degenerats: no determinen un pla \u00fanic.'}</p>${steps(['d(P,\u03c0)=|Ax+By+Cz+D|/\u221a(A\u00b2+B\u00b2+C\u00b2).','Projecci\u00f3 H=P-[(n\u00b7P+D)/(n\u00b7n)]n.'])}`);
 if(r.tool==='finance')html=resultPanel('Resultat del model escolar',metrics([[num(r.payment),'quota per per\u00edode'],[num(r.total),'suma de quotes'],[num(r.interest),'interessos del pr\u00e9stec']])+`<p>Capital final alternatiu en capitalitzaci\u00f3 composta, sense quotes: ${num(r.capitalized)}.</p>`+steps(['Quota: C\u00b7r/[1-(1+r)^(-n)] si r>0; si r=0, C/n.','Total de quotes: quota \u00b7 n. Interessos: total - capital inicial.','Escenari alternatiu d\u2019estalvi sense fluxos intermedis: C(1+r)^n. No sumar aquest capital al pr\u00e9stec.']));
 $('#lab-output').innerHTML=html+`<div class="actions no-print">${button('Desa el c\u00e0lcul al dossier','save-calculation','','secondary small')}${button('Imprimeix aquesta vista','print','','subtle small')}</div>`;
 if(r.tool==='calculus')drawGraph();
}
let job=0,jobTimer=null;
async function runTool(){let form=$('#tool-form');if(!form||!form.reportValidity())return;const tool=form.dataset.tool,p=Object.fromEntries(new FormData(form));state.lab[tool]=p;save();lastParams=p;lastResult=null;
 if(worker)worker.terminate();clearTimeout(jobTimer);const current=++job;
 $('#lab-output').innerHTML='<div class="panel"><h2>Calculant\u2026</h2><p>Validant el domini i les dades.</p></div>';$('#solve-button').disabled=true;
 const failed=msg=>{if(current!==job)return;clearTimeout(jobTimer);if($('#solve-button'))$('#solve-button').disabled=false;if($('#lab-output'))$('#lab-output').innerHTML=resultPanel('Cal revisar les dades',problem(msg));};
 try{worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(current!==job||!$('#lab-output'))return;clearTimeout(jobTimer);$('#solve-button').disabled=false;if(data.error){failed(data.error);return;}lastResult=data.result;lastParams=p;renderResult(lastResult,p);};worker.onerror=e=>failed('No s\u2019ha pogut executar el motor: '+e.message);worker.postMessage({id:current,tool,params:p});jobTimer=setTimeout(()=>{worker.terminate();failed('Temps m\u00e0xim de c\u00e0lcul (8 segons). Simplifica l\u2019expressi\u00f3 o treballa per parts.');},8000);}catch(e){failed(e.message);}
}
function graphHTML(r,p){return`<div class="graph-controls no-print">${[['xmin','x m\u00ednim',-4],['xmax','x m\u00e0xim',4],['ymin','y m\u00ednim',-6],['ymax','y m\u00e0xim',6]].map(([id,l,v])=>`<label>${l}<input id="g-${id}" type="number" value="${currentPreset?.plot?.[id]??v}" step="any"></label>`).join('')}</div><div class="graph-toggles no-print">${[['f','f(x)',true],['d','f\u2032(x)',false],['dd','f\u2032\u2032(x)',false],['t','Tangent',true],['s','Secant',false],['area','\u00c0rea',false]].map(([id,l,on])=>`<label><input id="g-${id}" type="checkbox" ${on?'checked':''}>${l}</label>`).join('')}</div><div class="actions no-print spaced"><label>Pas de la secant h <input id="g-h" type="range" min="0.01" max="3" step="0.01" value="1"></label><span id="g-h-label">h = 1</span>${button('Ajusta l\u2019eix y','fit-graph','','subtle small')}${button('Desa gr\u00e0fica PNG','save-graph','','secondary small')}</div><div id="graph-warning"></div><div class="graph-wrap"><canvas id="plot" role="img" aria-label="Gr\u00e0fica mostrejada de la funci\u00f3 i les corbes seleccionades. Taula de valors a continuaci\u00f3."></canvas></div><div class="legend"><span><b class="line-f"></b>f</span><span><b class="line-d"></b>f\u2032</span><span><b class="line-dd"></b>f\u2032\u2032</span><span><b class="line-t"></b>tangent / secant discont\u00ednua</span></div><p id="graph-position" class="hint">Mou el cursor per consultar x i f(x).</p><p class="figure-note">Tra\u00e7at num\u00e8ric. Els salts i els zeros de denominadors polin\u00f2mics detectats no s\u2019uneixen, per\u00f2 no s\u2019ha calculat un domini simb\u00f2lic complet. La finestra i el mostreig poden ocultar detalls.</p><details><summary>Taula de valors de la finestra</summary><div class="details-content" id="graph-table"></div></details>`;}
function graphLimits(){const vals=['xmin','xmax','ymin','ymax'].map(k=>Number($('#g-'+k).value));if(vals.some(v=>!Number.isFinite(v))||vals[0]>=vals[1]||vals[2]>=vals[3]||Math.max(...vals.map(Math.abs))>1e9||vals[1]-vals[0]<1e-8||vals[3]-vals[2]<1e-8)throw Error('Finestra inv\u00e0lida: calen l\u00edmits ordenats, finits i ben separats (escala m\u00e0xima 10\u2079).');return vals;}
function drawGraph(){if(!$('#plot')||lastResult?.tool!=='calculus')return;let bounds;try{bounds=graphLimits();$('#graph-warning').innerHTML='';}catch(e){$('#graph-warning').innerHTML=problem(e.message);return;}
 const [xl,xr,yl,yr]=bounds,r=lastResult,p=lastParams,c=$('#plot'),rect=c.getBoundingClientRect(),W=Math.max(220,rect.width),H=Math.max(240,rect.height),dpr=Math.min(2,window.devicePixelRatio||1);c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);
 const pad={l:48,r:18,t:20,b:33},w=W-pad.l-pad.r,h=H-pad.t-pad.b,X=x=>pad.l+(x-xl)/(xr-xl)*w,Y=y=>pad.t+(yr-y)/(yr-yl)*h;
 function tick(v){const z=Math.pow(10,Math.floor(Math.log10(v))),k=v/z;return(k>5?10:k>2?5:k>1?2:1)*z;}
 ctx.font='11px system-ui';ctx.textAlign='center';ctx.lineWidth=1;const tx=tick((xr-xl)/7),ty=tick((yr-yl)/7);
 for(let x=Math.ceil(xl/tx)*tx,k=0;x<=xr&&k<30;x+=tx,k++){ctx.strokeStyle='#e7edef';ctx.beginPath();ctx.moveTo(X(x),pad.t);ctx.lineTo(X(x),H-pad.b);ctx.stroke();ctx.fillStyle='#627780';ctx.fillText(num(Math.abs(x)<tx*1e-8?0:x),X(x),H-10);}
 ctx.textAlign='right';for(let y=Math.ceil(yl/ty)*ty,k=0;y<=yr&&k<30;y+=ty,k++){ctx.strokeStyle='#e7edef';ctx.beginPath();ctx.moveTo(pad.l,Y(y));ctx.lineTo(W-pad.r,Y(y));ctx.stroke();ctx.fillStyle='#627780';ctx.fillText(num(Math.abs(y)<ty*1e-8?0:y),pad.l-7,Y(y)+4);}
 ctx.strokeStyle='#8a9da5';ctx.lineWidth=1.3;if(xl<=0&&xr>=0){ctx.beginPath();ctx.moveTo(X(0),pad.t);ctx.lineTo(X(0),H-pad.b);ctx.stroke();}if(yl<=0&&yr>=0){ctx.beginPath();ctx.moveTo(pad.l,Y(0));ctx.lineTo(W-pad.r,Y(0));ctx.stroke();}
 let poles=[];try{poles=M.singularities(r.ast,xl,xr);}catch{}
 const domain=x=>Number.isFinite(M.safeValue(r.ast,x));ctx.save();ctx.beginPath();ctx.rect(pad.l,pad.t,w,h);ctx.clip();
 if($('#g-area').checked){let lo=Number(p.lo.replace(',','.')),hi=Number(p.hi.replace(',','.'));if(lo>hi)[lo,hi]=[hi,lo];ctx.lineWidth=Math.max(1,w/500);for(let i=0;i<=500;i++){const x=xl+(xr-xl)*i/500,y=M.safeValue(r.ast,x);if(x>=lo&&x<=hi&&Number.isFinite(y)){ctx.strokeStyle=y>=0?'#14798928':'#bb5b2630';ctx.beginPath();ctx.moveTo(X(x),Y(0));ctx.lineTo(X(x),Y(y));ctx.stroke();}}}
 function curve(f,color,dash=false){ctx.strokeStyle=color;ctx.lineWidth=2.2;ctx.setLineDash(dash?[7,5]:[]);ctx.beginPath();let prev=null;for(let i=0;i<=1000;i++){let x=xl+(xr-xl)*i/1000,y=domain(x)?f(x):NaN;const current=Number.isFinite(y)&&Math.abs(y)<1e12?{x,y}:null;let join=current&&prev&&Math.abs(Y(y)-Y(prev.y))<H*1.4&&!poles.some(t=>t>=prev.x&&t<=x);if(current){if(join)ctx.lineTo(X(x),Y(y));else ctx.moveTo(X(x),Y(y));}prev=current;}ctx.stroke();ctx.setLineDash([]);}
 if($('#g-f').checked)curve(x=>M.safeValue(r.ast,x),'#147989');if($('#g-d').checked)curve(x=>M.safeValue(r.d,x),'#bb5b26');if($('#g-dd').checked)curve(x=>M.safeValue(r.dd,x),'#7464ae');
 const hSec=Number($('#g-h').value);$('#g-h-label').textContent='h = '+num(hSec);
 if(r.point){const{a,y,slope}=r.point;if($('#g-t').checked)curve(x=>y+slope*(x-a),'#455967',true);if($('#g-s').checked){let y2=M.safeValue(r.ast,a+hSec);if(Number.isFinite(y2))curve(x=>y+(y2-y)/hSec*(x-a),'#bd962b',true);}
 ctx.beginPath();ctx.arc(X(a),Y(y),4,0,2*Math.PI);ctx.fillStyle='#147989';ctx.fill();}
 ctx.restore();$('#graph-table').innerHTML=mtable(Array.from({length:7},(_,i)=>{const x=xl+(xr-xl)*i/6;return[x,M.safeValue(r.ast,x),domain(x)?M.safeValue(r.d,x):NaN];}),['x','f(x)','f\u2032(x)']);
 c.onpointermove=event=>{let bb=c.getBoundingClientRect(),x=xl+((event.clientX-bb.left)-pad.l)/w*(xr-xl);if(x>=xl&&x<=xr)$('#graph-position').textContent='x \u2248 '+num(x)+'   \u00b7   f(x) \u2248 '+num(M.safeValue(r.ast,x));};
}
function fitGraph(){if(lastResult?.tool!=='calculus')return;let [xl,xr]=graphLimits(),ys=Array.from({length:501},(_,i)=>M.safeValue(lastResult.ast,xl+(xr-xl)*i/500)).filter(Number.isFinite).sort((a,b)=>a-b);if(!ys.length){toast('No hi ha valors definits en aquesta finestra.');return;}let a=ys[Math.floor(ys.length*.03)],b=ys[Math.min(ys.length-1,Math.floor(ys.length*.97))],margin=Math.max((b-a)*.15,.5);$('#g-ymin').value=M.fmt(a-margin);$('#g-ymax').value=M.fmt(b+margin);drawGraph();}
async function refreshDiagnostics(){if(!$('#diagnostics'))return;let n=0;try{const names=await caches.keys();for(const name of names){if(name.startsWith('mates-batx-')&&name.includes(encodeURIComponent(new URL('.',location.href).pathname))){const ca=await caches.open(name);n+=(await ca.keys()).length;}}}catch{}
 const secure=location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname);$('#diagnostics').innerHTML=`<p><strong>Versi\u00f3:</strong> 2.0.0 \u00b7 ${secure?'origen apte per a PWA':'cal HTTPS o localhost'}</p><p><strong>Connexi\u00f3:</strong> ${navigator.onLine?'el navegador indica connexi\u00f3':'sense connexi\u00f3'}</p><p><strong>Control offline:</strong> ${navigator.serviceWorker?.controller?'actiu':'pendent de primera activaci\u00f3'}</p><p><strong>Fitxers en mem\u00f2ria cau:</strong> ${n}. ${n>10?'C\u00f2pia local preparada.':'La primera c\u00e0rrega encara pot estar pendent.'}</p><p><strong>PAU originals:</strong> enlla\u00e7os externs, no desats offline.</p>`;}
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark');$('#course').value=state.course;}
function connection(){ $('#connection').textContent=navigator.onLine?'Eines locals disponibles':'Sense connexi\u00f3 \u00b7 mode local';}
function exportData(){dl('mates-docent-copia-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2));toast('C\u00f2pia exportada. Conserva-la fora del navegador.');}
function initPlan(c){if(!state.plans[c])state.plans[c]=structuredClone(PL[c]);return state.plans[c];}
function addExercise(e){if(state.exercises.some(x=>x.id===e.id)){toast('Aquest exercici ja \u00e9s al dossier.');return;}if(state.exercises.length>=1000)throw Error('El dossier ha arribat al l\u00edmit de 1000 exercicis. Exporta una c\u00f2pia.');state.exercises.push(e);save();toast('Exercici desat al dossier.');}
async function clickAction(a){const action=a.dataset.action,id=a.dataset.id;
 if(action==='favorite'){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();a.textContent=state.favorites.includes(id)?'\u2605 Preferit':'\u2606 Desa com a preferit';}
 if(action==='select-question'){state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];save();a.textContent=state.selected.includes(id)?'\u2713 Al dossier':'\uff0b Dossier';if(location.hash==='#workbook')route();}
 if(action==='add-example'){const[t,i]=id.split(':'),e=topic(t).examples[+i];addExercise({...e,id:'example-'+id,title:topic(t).title,topic:t,origin:'Exemple propi del temari'});}
 if(action==='generate'){let e=generateExercise($('#gen-family').value,Number($('#gen-seed').value)),family=$('#gen-family').value,seed=$('#gen-seed').value;addExercise(e);route();$('#gen-family').value=family;$('#gen-seed').value=String(Number(seed)+1);}
 if(action==='remove-exercise'){if(!confirm('Elimina aquest exercici del dossier?'))return;state.exercises=state.exercises.filter(e=>e.id!==id);save();route();}
 if(action==='print'){window.print();}
 if(action==='export'){exportData();}
 if(action==='export-comparison'){dl('comparativa-pau-curriculum.json',JSON.stringify({scope:'Ordinaria i extraordinaria 2024-2026, per prova, no per puntuacio',reviewed:'2026-10-01',rows:comparisonData()},null,2));}
 if(action==='reset-plan'){if(!confirm('Restaura l\u2019ordre i les sessions de la proposta? Les notes es conservaran.'))return;delete state.plans[id];for(const k of Object.keys(state.hours))if(k.startsWith(id+':'))delete state.hours[k];save();route();}
 if(action==='plan-up'||action==='plan-down'){const[c,tr,tid]=id.split(':'),arr=initPlan(c)[+tr],i=arr.indexOf(tid),j=i+(action==='plan-up'?-1:1);if(i>=0&&j>=0&&j<arr.length){[arr[i],arr[j]]=[arr[j],arr[i]];save();route();}}
 if(action==='project'){document.body.classList.toggle('projection');$$('[data-action=project]').forEach(b=>b.textContent=document.body.classList.contains('projection')?'Surt de projecci\u00f3':'Mode projecci\u00f3');setTimeout(drawGraph,60);}
 if(action==='tool-defaults'){state.lab[id]={...TOOLS[id].defaults};save();history.replaceState(null,'','#lab/'+id);route();}
 if(action==='fit-graph')fitGraph();
 if(action==='save-graph'){const c=$('#plot');if(c)c.toBlob(b=>{const url=URL.createObjectURL(b),el=document.createElement('a');el.href=url;el.download='grafica-matematiques.png';el.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 if(action==='save-calculation'){if(!lastResult)return;const text=$('#lab-output').innerText;addExercise({id:'calc-'+Date.now(),title:TOOLS[lastResult.tool].title,question:'Dades: '+JSON.stringify(lastParams),steps:text.split('\n').filter(s=>s.trim()).slice(0,300),origin:'C\u00e0lcul local desat \u00b7 revisa les hip\u00f2tesis',topic:'algebra'});}
 if(action==='install-help')$('#help-dialog').showModal();
 if(action==='check-update'){if(swRegistration){await swRegistration.update();toast(swRegistration.waiting?'Hi ha una versi\u00f3 nova pendent.':'Comprovaci\u00f3 sol\u00b7licitada.');await refreshDiagnostics();}else toast('El service worker no est\u00e0 actiu en aquest origen.');}
 if(action==='reset-data'){if(!confirm('Esborrar notes, pla, preferits i dossier d\u2019aquest navegador? Aquesta acci\u00f3 no es pot desfer sense c\u00f2pia JSON.'))return;state=initial();save();applyTheme();route();}
}
document.addEventListener('click',e=>{if(e.target.closest('a.skip')){e.preventDefault();$('#main').focus();return;}const a=e.target.closest('[data-action]');if(a){e.preventDefault();Promise.resolve(clickAction(a)).catch(err=>toast(err.message));}});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.note){state.notes[el.dataset.note]=el.value.slice(0,30000);save();}if(el.id==='topic-search')renderTopicGrid();if(el.id==='exam-search')renderExams();if(el.id?.startsWith('g-'))drawGraph();});
document.addEventListener('change',async e=>{const el=e.target;try{
 if(el.id==='course'){state.course=el.value;save();route();}
 if(['topic-block','topic-favorites'].includes(el.id))renderTopicGrid();
 if(['exam-track','exam-year','exam-session'].includes(el.id))renderExams();
 if(['compare-track','compare-level'].includes(el.id))renderComparison();
 if(el.dataset.status){state.status[el.dataset.status]=el.value;save();toast('Estat desat.');}
 if(el.dataset.hours){const v=Number(el.value);if(!Number.isInteger(v)||v<0||v>200)throw Error('Cal un nombre enter de sessions entre 0 i 200.');state.hours[el.dataset.hours]=v;save();route();}
 if(el.dataset.moveTopic){const {moveTopic:id,course:c,from}=el.dataset,to=Number(el.value),plan=initPlan(c);plan[+from]=plan[+from].filter(x=>x!==id);if(!plan[to].includes(id))plan[to].push(id);save();route();}
 if(el.id==='tool-select')location.hash='lab/'+el.value;
 if(el.id==='import-file'){const f=el.files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('La c\u00f2pia supera els 2 MB.');const candidate=validateState(JSON.parse(await f.text()));if(!confirm('Substituir totes les dades locals per aquesta c\u00f2pia? Exporta les actuals abans de continuar.')){el.value='';return;}state=candidate;save();applyTheme();route();toast('C\u00f2pia importada i validada.');}
 }catch(err){toast(err.message);if(el.id==='import-file')el.value='';}
});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='tool-form')runTool();if(e.target.id==='custom-form'){let f=Object.fromEntries(new FormData(e.target));try{addExercise({id:'own-'+Date.now(),title:f.title,question:f.question,steps:f.steps.split('\n').filter(s=>s.trim()),origin:'Exercici propi del docent',topic:'algebra'});route();}catch(err){toast(err.message);}}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&$('#tool-form')){e.preventDefault();runTool();}if(e.key==='Escape'&&document.body.classList.contains('projection')){document.body.classList.remove('projection');document.querySelector('[data-action="project"]')?.replaceChildren(document.createTextNode('Mode projecci\u00f3'));setTimeout(drawGraph,80);}});
$('#theme').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();save();drawGraph();});
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));});
$('#print').addEventListener('click',()=>window.print());$('#close-dialog').addEventListener('click',()=>$('#help-dialog').close());
$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}else $('#help-dialog').showModal();});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('online',connection);window.addEventListener('offline',connection);window.addEventListener('resize',()=>{clearTimeout(window.graphResizeTimer);window.graphResizeTimer=setTimeout(drawGraph,150);});
window.addEventListener('hashchange',()=>{++job;clearTimeout(jobTimer);worker?.terminate();route();});
// Expand all educational details for printing, then restore the exact on-screen state.
let printDetails=[];window.addEventListener('beforeprint',()=>{printDetails=$$('main details:not([open])');printDetails.forEach(d=>d.open=true);});window.addEventListener('afterprint',()=>{printDetails.forEach(d=>d.open=false);printDetails=[];drawGraph();});
async function setupSW(){if(!('serviceWorker'in navigator)||location.protocol==='file:')return;try{
 swRegistration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});
 const show=()=>{if(swRegistration.waiting)$('#update-banner').classList.remove('hidden');};show();swRegistration.addEventListener('updatefound',()=>{const w=swRegistration.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'){if(navigator.serviceWorker.controller)show();else setTimeout(refreshDiagnostics,800);}});});
 let updating=false;$('#update').addEventListener('click',()=>{updating=true;swRegistration.waiting?.postMessage({type:'SKIP_WAITING'});});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updating)location.reload();else refreshDiagnostics();});await navigator.serviceWorker.ready;refreshDiagnostics();
 }catch(e){if($('#diagnostics'))$('#diagnostics').innerHTML=problem('No s\u2019ha completat la preparaci\u00f3 offline: '+e.message);}}
async function init(){applyTheme();connection();try{
 [T,EX,PL,PRE]=await Promise.all(['topics','exams','plans','presets'].map(async name=>{const res=await fetch('./data/'+name+'.json');if(!res.ok)throw Error('No es pot carregar '+name);return res.json();}));Q=EX.flatMap(e=>e.questions);route();window.appReady=true;setupSW();
 }catch(e){$('#main').innerHTML=resultPanel('No s\u2019ha pogut carregar l\u2019app',problem(e.message)+'<p>Cal publicar <strong>tota</strong> la carpeta a GitHub Pages (HTTPS), o executar un servidor local. Obrir nom\u00e9s index.html amb doble clic no \u00e9s una instal\u00b7laci\u00f3 PWA.</p>');}}
init();

function presetLinks(qid){const ps=PRE.filter(p=>p.question===qid);return ps.length?`<div class="actions spaced no-print">${ps.map(p=>`<a class="button subtle small" href="#lab/${p.tool}?preset=${p.id}">${E(p.label)} \u2192</a>`).join('')}</div>`:'';}
function presetNotice(){if(!currentPreset)return'';const p=currentPreset,q=Q.find(q=>q.id===p.question),e=EX.find(e=>e.id===q.exam);return `<section class="notice"><p><strong>Fragment PAU carregat: ${E(p.label)}</strong></p><p>${E(p.note)}</p><p>${sourceLink(e.url+'#page='+q.page,'Enunciat '+e.year+' \u00b7 exercici '+q.label)} \u00b7 ${sourceLink(e.correction+'#page='+p.correctionPage,'Criteri oficial de refer\u00e8ncia')}</p><p>Prem \u00abCalcula i explica\u00bb. Nom\u00e9s s\u2019han carregat les dades indicades; els passos locals no substitueixen la correcci\u00f3 oficial completa.</p></section>`;}
