import * as M from './engine.mjs';
/** Reproducible, constructive examples; deliberately separate from official PAU questions. */
export function generateExercise(family,seed){
 if(!Number.isSafeInteger(Number(seed)))throw Error('La llavor ha de ser un enter segur.');
 seed=Number(seed);let a=seed>>>0;const rand=()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};
 const I=(l,r)=>l+Math.floor(rand()*(r-l+1)),F=M.fmt;
 const e={id:'gen-'+family+'-'+seed,title:'',question:'',steps:[],origin:'Variant pr\u00f2pia \u00b7 llavor '+seed,topic:'algebra'};
 if(family==='quadratic'){const r=I(-6,6),s=I(-6,6),k=I(1,4),p=[k*r*s,-k*(r+s),k];e.title='Equaci\u00f3 quadr\u00e0tica';e.question='Resol '+M.ptext(p)+' = 0.';e.steps=['Identificar a='+k+', b='+p[1]+', c='+p[0]+'.','Factoritzar: '+k+'(x-('+r+'))(x-('+s+'))=0.',r===s?'Arrel doble: x='+r+'.':'Arrels: x='+r+' i x='+s+'.','Substituir cada arrel a l\u2019expressi\u00f3 inicial: el residu \u00e9s zero.'];}
 else if(family==='derivative'){const p=[I(-6,6),I(-5,5),I(1,4)],x=I(-3,3),d=M.pdiff(p),y=M.peval(p,x),m=M.peval(d,x);e.title='Derivada i recta tangent';e.topic='derivative';e.question='Troba la tangent a f(x)='+M.ptext(p)+' quan x='+x+'.';e.steps=['f\u2032(x)='+M.ptext(d)+'.','Punt de contacte: ('+x+', '+F(y)+'). Pendent f\u2032('+x+')='+F(m)+'.','Equaci\u00f3: y - ('+F(y)+') = '+F(m)+'[x - ('+x+')].','Forma expl\u00edcita: y='+F(m)+'x + ('+F(y-m*x)+'). La tangent passa pel punt i t\u00e9 el pendent calculat.'];}
 else if(family==='integral'){const k=I(1,5),b=I(0,4),r=I(1,5),p=[b,k],prim=[0,b,k/2],val=M.peval(prim,r);e.title='Acumulaci\u00f3 i integral definida';e.topic='integral';e.question='Calcula la integral de '+M.ptext(p)+' entre 0 i '+r+' i interpreta\u2019n el signe.';e.steps=['Una primitiva \u00e9s F(x)='+M.ptext(prim)+'.','Per Barrow, F('+r+') - F(0) = '+F(val)+'.','La funci\u00f3 \u00e9s no negativa en tot l\u2019interval; aquesta integral coincideix amb l\u2019\u00e0rea geom\u00e8trica.','Comprovaci\u00f3: F\u2032(x)='+M.ptext(p)+'.'];}
 else if(family==='system'){const x=I(-5,5),y=I(-5,5),a=I(1,5),b=I(1,5),c=a+1,d=b;let det=a*d-b*c;const u=a*x+b*y,v=c*x+d*y;e.title='Model i sistema 2\u00d72';e.topic='systems';e.question='Resol '+a+'x+'+b+'y='+u+'; '+c+'x+'+d+'y='+v+'.';e.steps=['Determinant: '+a+'\u00b7'+d+' - '+b+'\u00b7'+c+' = '+det+' \u2260 0. Per tant, SCD.','Eliminaci\u00f3 o Cramer: x=('+u+'\u00b7'+d+' - '+b+'\u00b7'+v+')/'+det+' = '+x+'.','y=('+a+'\u00b7'+v+' - '+u+'\u00b7'+c+')/'+det+' = '+y+'.','Comprovar les dues igualtats per substituci\u00f3.'];}
 else if(family==='binomial'){const n=I(6,15),p=I(2,8)/10,k=I(1,n-1),v=M.binomial(n,p,k,k).probability;e.title='Model binomial';e.topic='binomial';e.question='En '+n+' assajos independents, amb probabilitat d\u2019\u00e8xit '+p+' constant, calcula P(X='+k+').';e.steps=['X segueix B('+n+', '+p+'). Cal nombre fix d\u2019assajos, independ\u00e8ncia i probabilitat constant.','P(X=k)=C(n,k) p^k (1-p)^(n-k).','Substituint: C('+n+','+k+')\u00b7'+p+'^'+k+'\u00b7'+F(1-p)+'^'+(n-k)+' \u2248 '+F(v)+'.','La probabilitat no \u00e9s n\u00b7p: aquest producte \u00e9s l\u2019esperan\u00e7a, aqu\u00ed '+F(n*p)+'.'];}
 else if(family==='bayes'){const p=I(2,8)/10,l=I(1,4)/10,r=I(5,9)/10,b=M.bayes([p,1-p],[l,r]);e.title='Probabilitat total i Bayes';e.topic='bayes';e.question='Dues l\u00ednies produeixen proporcions '+p+' i '+F(1-p)+'. La probabilitat d\u2019un control positiu \u00e9s '+l+' a A i '+r+' a B. Donat un positiu, quina \u00e9s la probabilitat que provingui d\u2019A?';e.steps=['P(A\u2229+)='+p+'\u00b7'+l+'='+F(b.joint[0])+'.','P(+)='+F(b.joint[0])+'+'+F(b.joint[1])+'='+F(b.evidence)+'.','P(A|+)=P(A\u2229+)/P(+) \u2248 '+F(b.posterior[0])+'.','Diferencia P(+|A) de P(A|+): condicionen universos diferents.'];}
 else if(family==='optimization'){const h=I(4,12),k=I(1,5),v=I(40,100),p=[v-k*h*h,2*k*h,-k];e.title='Optimitzaci\u00f3 amb comprovaci\u00f3 global';e.topic='optimize';e.question='Troba el m\u00e0xim de B(x)='+M.ptext(p)+' per a 0\u2264x\u2264'+(2*h)+'.';e.steps=['B\u2032(x)='+M.ptext(M.pdiff(p))+'. Igualar a zero dona x='+h+'.','B\u2032\u2032(x)='+(-2*k)+'<0: \u00e9s un m\u00e0xim local.','Comprovar l\u2019interval tancat: B(0)=B('+(2*h)+')='+p[0]+', mentre que B('+h+')='+v+'.','El m\u00e0xim global s\u2019assoleix a x='+h+' i val '+v+'.'];}
 else if(family==='confidence'){const center=I(30,80),sigma=I(4,12),n=I(6,15)**2,r=M.confidence('known',center,sigma,n,.95);e.title='Interval normal per a una mitjana';e.topic='inference';e.question='Una mostra aleat\u00f2ria independent de mida '+n+' t\u00e9 mitjana '+center+'. La desviaci\u00f3 poblacional coneguda \u00e9s '+sigma+'. Construeix l\u2019IC del 95% per a la mitjana poblacional (poblaci\u00f3 normal).';e.steps=['Error est\u00e0ndard: \u03c3/\u221an \u2248 '+F(r.se)+'.','Quantil z(0,975) \u2248 '+F(r.z)+'; marge z\u03c3/\u221an \u2248 '+F(r.margin)+'.','Interval: ['+F(r.lo)+', '+F(r.hi)+'].','El 95% fa refer\u00e8ncia al percentatge de cobertura del procediment en repeticions del mostreig, no al 95% dels individus.'];}
 else throw Error('Fam\u00edlia desconeguda.');
 return e;
}
