import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as M from '../js/engine.mjs';
import {solve} from '../js/solver.mjs';
import {generateExercise} from '../js/generator.mjs';
let passed=0,failed=0,failures=[];
function test(name,fn){try{fn();passed++;}catch(e){failed++;failures.push({name,error:e.message});console.error('FAIL',name,e.message);}}
const close=(a,b,tol=1e-8)=>assert.ok(Number.isFinite(a)&&Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const expr=(s,x)=>M.value(M.parse(s),x);
for(const [s,x,v]of [['-x^2',3,-9],['(-x)^2',3,9],['2^3^2',0,512],['2x+3(x-1)',2,7],['2,5*x',2,5],['1e-3*x',2,.002],['sin(pi/2)',0,1],['log(e)',0,1],['sqrt(4)',0,2],['abs(-3)',0,3],['2^-2',0,.25],['x/x',2,1],['2*(3+4)',0,14]])test('parser '+s,()=>close(expr(s,x),v));
for(const s of ['','alert(1)','x=2','window.location','x;1','constructor(2)','sin x','x+)2(','1/0','ln(-1)','sqrt(-1)','0^0','exp(10000)'])test('reject '+s,()=>assert.throws(()=>expr(s,0)));
for(const x of [-1,0,1])test('domain reciprocal '+x,()=>x===0?assert.throws(()=>expr('1/x',x)):close(expr('1/x',x),1/x));
const derivatives=[['x^3-3*x',x=>3*x*x-3],['(2*x+1)^5',x=>10*(2*x+1)**4],['sin(3*x)',x=>3*Math.cos(3*x)],['cos(x)',x=>-Math.sin(x)],['tan(x)',x=>1/Math.cos(x)**2],['exp(2*x)',x=>2*Math.exp(2*x)],['ln(3*x^2+1)',x=>6*x/(3*x*x+1)],['sqrt(x+3)',x=>1/(2*Math.sqrt(x+3))],['(x+1)/(x-2)',x=>-3/(x-2)**2],['asin(x/2)',x=>.5/Math.sqrt(1-x*x/4)],['atan(x)',x=>1/(1+x*x)],['2^x',x=>2**x*Math.log(2)],['x^x',x=>x**x*(Math.log(x)+1)]];
for(const [s,expected]of derivatives)for(const x of [.2,.7,1.1])test('derivative '+s+' at '+x,()=>close(M.value(M.derivative(M.parse(s)),x),expected(x)));
for(const s of ['x^4+2*x-3','sin(2*x+1)','cos(3*x-2)','exp(2*x)','1/(3*x+2)','(3*x+2)^-1','(2*x+1)^3','sqrt(x+3)','2*sin(x)+3*cos(2*x)'])for(const x of [.1,.7,1.3])test('primitive reverse '+s+' at '+x,()=>{const a=M.parse(s),F=M.primitive(a);close(M.value(M.derivative(F),x),M.value(a,x),1e-7);});
test('unsupported primitive honest',()=>assert.throws(()=>M.primitive(M.parse('sin(x^2)'))));
for(const [s,l,r,area,v]of [['x^2',0,1,false,1/3],['sin(x)',0,Math.PI,false,2],['exp(x)',0,1,false,Math.E-1],['x',-1,1,false,0],['x',-1,1,true,1],['x^2',1,0,false,-1/3],['x',1,-1,true,1],['x^2',1,1,false,0],['3*x^2+2',-1,2,false,15]])test('integral '+s+' '+l+' '+r+' '+area,()=>close(M.integrate(M.parse(s),l,r,area).value,v,2e-7));
for(const [s,l,r]of [['1/x',-1,1],['1/(x-0.123)',0,1],['ln(x)',0,1],['sqrt(x)',-1,1],['1/(x^2-2)',0,2]])test('reject invalid integral '+s,()=>assert.throws(()=>M.integrate(M.parse(s),l,r)));
for(const [s,a,L,R]of [['(x^2-1)/(x-1)',1,2,2],['1/x',0,-Infinity,Infinity],['1/x^2',0,Infinity,Infinity],['x^2',Infinity,Infinity,Infinity],['1/x',Infinity,0,0],['(2*x^2+1)/(x^2-3)',-Infinity,2,2],['1/(x-0.0000000001)',0,-1e10,-1e10],['0/x',0,0,0]])test('limit '+s+' '+a,()=>{const r=M.limit(M.parse(s),a);for(const[k,v]of[['left',L],['right',R]])Number.isFinite(v)?close(r[k],v):assert.equal(r[k],v);});
test('exploratory nonrational limit',()=>assert.throws(()=>M.limit(M.parse('sin(x)/x'),0)));
for(const [p,rs]of [[[ -2,-1,1],[-1,2]],[[1,0,1],[]],[[0,0,1],[0]],[[1,-2,1],[1]],[[1e-12,0,1],[]],[[0,-1,0,1],[-1,0,1]],[[0,0,0,1],[0]],[[1e-15,-2e-15],[.5]],[[2],[ ]],[[0],[]]])test('roots '+JSON.stringify(p),()=>{let r=M.roots(p);assert.equal(r.length,rs.length);r.forEach((x,i)=>close(x,rs[i],1e-6));});
for(let i=1;i<=20;i++)test('constructed cubic '+i,()=>{let known=[-i,-.25,i+1],p=[1];known.forEach(r=>p=M.pmul(p,[-r,1]));const rs=M.roots(p);assert.equal(rs.length,3);rs.forEach((r,j)=>close(r,known[j],1e-7));});
test('quadratic complex no real roots',()=>{let r=solve('equation',{f:'x^2+1e-12',mode:'polynomial'});assert.equal(r.roots.length,0);close(r.complex.imaginary,1e-6);});
test('degenerate linear',()=>{let r=solve('equation',{f:'0*x^2+2*x-4'});assert.equal(r.degree,1);close(r.roots[0].x,2);});
test('zero polynomial',()=>assert.equal(solve('equation',{f:'0'}).identity,true));
test('nonzero constant',()=>assert.equal(solve('equation',{f:'2'}).identity,false));
test('bisection cubic',()=>{let r=M.bisect(M.parse('x^3+x-1'),0,1);close(expr('x^3+x-1',r.root),0);});
test('bisection degree 13 PAU structure',()=>{let r=M.bisect(M.parse('3*x^13+5*x^3+2'),-1,0);close(expr('3*x^13+5*x^3+2',r.root),0);});
test('bisection rejects pole',()=>assert.throws(()=>M.bisect(M.parse('1/x'),-1,1)));
test('bisection no sign change',()=>assert.throws(()=>M.bisect(M.parse('x^2+1'),-1,1)));
for(const[A,kind,solution]of [[[ [1,1,3],[1,-1,1]],'SCD',[2,1]],[[[1,1,2],[2,2,4]],'SCI',[2,0]],[[[1,1,2],[2,2,5]],'SI',null],[[[0,0,0],[0,0,0]],'SCI',[0,0]],[[[0,0,1],[0,0,0]],'SI',null],[[[0,1,2],[1,0,1]],'SCD',[1,2]],[[[1,0,1e12],[0,1,2e12]],'SCD',[1e12,2e12]],[[[1e-12,0,1e-12],[0,1e-12,2e-12]],'SCD',[1,2]]])test('gauss '+JSON.stringify(A),()=>{let r=M.gauss(A);assert.equal(r.kind,kind);if(solution)r.particular.forEach((x,i)=>close(x,solution[i]));for(const v of r.basis)A.forEach(row=>close(M.dot(row.slice(0,-1),v),0));});
test('rectangular system',()=>{const r=M.gauss([[1,1,1,6],[1,0,1,4]]);assert.equal(r.kind,'SCI');assert.equal(r.rank,2);});
for(const A of [[[1,2],[3,4]],[[1,2,3],[0,1,4],[5,6,0]],[[.00001,0],[0,.00002]]])test('inverse '+JSON.stringify(A),()=>{let r=M.multiply(A,M.inverse(A));r.forEach((row,i)=>row.forEach((x,j)=>close(x,i===j?1:0)));});
test('inverse singular',()=>assert.throws(()=>M.inverse([[1,1],[2,2]])));
test('matrix multiply',()=>assert.deepEqual(M.multiply([[1,2],[3,4]],[[2,0],[1,2]]),[[4,4],[10,8]]));
test('matrix mismatch',()=>assert.throws(()=>M.multiply([[1,2]],[[1,2]])));
test('matrix parser decimal comma',()=>assert.deepEqual(M.matrix('1,5 2;3 4'),[[1.5,2],[3,4]]));
test('matrix parser rejects empty cell rows',()=>assert.throws(()=>M.matrix('1 2\n3')));
test('parameter special SCI',()=>{let r=M.parametric('1 1 2;1 m m+1',1);close(r.exceptions[0],1);assert.equal(r.special[0].kind,'SCI');assert.equal(r.at.kind,'SCI');});
test('parameter special SI',()=>assert.equal(M.parametric('1 1 2;1 m 3',1).special[0].kind,'SI'));
test('parameter zero determinant',()=>{let r=M.parametric('m m 1;1 1 2',2);assert.equal(r.exceptions,null);assert.equal(r.at.kind,'SI');});
test('bayes',()=>{let r=M.bayes([.6,.4],[.1,.3]);close(r.evidence,.18);close(r.posterior[0],1/3);close(r.posterior.reduce((s,x)=>s+x,0),1);});
for(const[p,l]of [[[.4,.4],[.2,.2]],[[1],[0]],[[1],[-.5]]])test('bayes invalid '+JSON.stringify([p,l]),()=>assert.throws(()=>M.bayes(p,l)));
for(const[n,p,l,h,v]of [[10,.5,0,10,1],[10,.5,5,5,252/1024],[1,.2,1,1,.2],[10,0,0,0,1],[10,1,10,10,1],[10,1,0,9,0],[10000,.5,0,10000,1]])test('binomial '+[n,p,l,h],()=>close(M.binomial(n,p,l,h).probability,v,1e-10));
test('binomial symmetry large',()=>close(M.binomial(2500,.5,0,1249).probability,(1-M.binomial(2500,.5,1250,1250).probability)/2));
for(const p of [-.1,1.1])test('binomial p '+p,()=>assert.throws(()=>M.binomial(10,p,0,10)));
for(const n of [0,1.5,10001])test('binomial n '+n,()=>assert.throws(()=>M.binomial(n,.5,0,n)));
test('normal standard',()=>close(M.normal(0,1,-1.96,1.96).probability,.9500042097,2e-7));
test('normal full',()=>close(M.normal(20,3,-Infinity,Infinity).probability,1));
test('normal zero interval',()=>close(M.normal(0,1,1,1).probability,0));
test('normal sigma zero',()=>assert.throws(()=>M.normal(0,0,-1,1)));
for(const q of [.01,.025,.5,.975,.99])test('normal inverse '+q,()=>close(M.normalCDF(M.invNormal(q)),q,2e-7));
test('confidence known',()=>{let r=M.confidence('known',50,10,100,.95);close(r.margin,1.9599639845,2e-6);close(r.lo+r.hi,100);});
test('confidence proportion',()=>{let r=M.confidence('proportion',.6,1,100,.95);close(r.se,Math.sqrt(.24/100));});
test('confidence sample too small',()=>assert.throws(()=>M.confidence('sample',50,10,12,.95)));
test('confidence Wald invalid',()=>assert.throws(()=>M.confidence('proportion',.99,1,100,.95)));
test('confidence type invalid',()=>assert.throws(()=>M.confidence('unknown',1,1,100,.95)));
test('descriptive',()=>{let r=M.statistics([1,2,3,4,5]);close(r.mean,3);close(r.median,3);close(r.sdPopulation,Math.sqrt(2));close(r.sdSample,Math.sqrt(2.5));});
test('regression',()=>{let r=M.statistics([1,2,3],[3,5,7]);close(r.slope,2);close(r.intercept,1);close(r.r,1);});
test('constant correlation undefined',()=>assert.throws(()=>M.statistics([1,1,1],[2,3,4])));
test('geometry triangle projection',()=>{const r=M.geometry([0,0,1],[2,0,1],[0,3,1],[0,0,1,0]);close(r.area,3);close(r.angle,90);close(r.distance,1);assert.deepEqual(r.projection,[0,0,0]);});
test('geometry collinear',()=>assert.equal(M.geometry([0,0,0],[1,1,1],[2,2,2],[1,0,0,0]).planeThrough,null));
test('geometry zero normal',()=>assert.throws(()=>M.geometry([0,0,0],[1,0,0],[0,1,0],[0,0,0,1])));
test('finance zero rate',()=>close(M.finance(1200,0,12).payment,100));
test('finance small rate',()=>close(M.finance(1200,1e-12,12).payment,100,1e-9));
test('finance standard',()=>close(M.finance(10000,.005,24).payment,443.2061025,1e-8));
test('finance overflow rejected',()=>assert.throws(()=>M.finance(10000,1000,1000)));
for(const family of ['quadratic','derivative','integral','system','binomial','bayes','optimization','confidence'])for(const seed of [1,17,2026,92764])test('generator '+family+' '+seed,()=>{const a=generateExercise(family,seed),b=generateExercise(family,seed);assert.deepEqual(a,b);assert.equal(a.id,'gen-'+family+'-'+seed);assert.ok(a.steps.length>=3);assert.ok(a.question.length>20);});
const base=new URL('../data/',import.meta.url);let T=JSON.parse(await readFile(new URL('topics.json',base))),E=JSON.parse(await readFile(new URL('exams.json',base))),P=JSON.parse(await readFile(new URL('plans.json',base)));
test('31 independent topics',()=>assert.equal(T.length,31));
test('12 papers, 64 records',()=>{assert.equal(E.length,12);assert.equal(E.flatMap(e=>e.questions).length,64);});
test('unique source IDs',()=>assert.equal(new Set(E.flatMap(e=>e.questions).map(q=>q.id)).size,64));
for(const e of E)test('source structure '+e.id,()=>{assert.ok(e.url.startsWith('https://universitats.gencat.cat/'));assert.ok(e.correction.startsWith('https://universitats.gencat.cat/'));assert.equal(e.questions.length,e.year===2024?6:5);for(const q of e.questions){assert.ok(q.page>0);assert.equal(q.exam,e.id);assert.equal(q.points,2.5);q.topics.forEach(id=>assert.ok(T.find(t=>t.id===id),id));}});
for(const t of T)test('topic structure '+t.id,()=>{assert.ok(t.idea.length>50);assert.ok(t.formulas.length);assert.ok(t.sequence.length>=3);assert.ok(t.errors.length>=2);assert.ok(t.examples.length);t.courses.forEach(c=>assert.ok(t.source[c.slice(0,3)],c));});
for(const[c,plan]of Object.entries(P))test('plan '+c,()=>{assert.equal(plan.length,3);assert.equal(new Set(plan.flat()).size,plan.flat().length);plan.flat().forEach(id=>assert.ok(T.find(t=>t.id===id)));});

for(const x of [-2,-1,1,2])test('negative integer exponent '+x,()=>{const a=M.parse('x^-2');close(M.value(M.derivative(a),x),-2/x**3);close(M.value(M.derivative(M.primitive(a)),x),1/x**2);});
for(const[s,l,r]of [['tan(x)',0,2],['1/sin(x)',3,4],['1/cos(2*x)',0,1],['ln(abs(x))',-1,1],['x^-1',-1,1]])test('transcendental singularity '+s,()=>assert.throws(()=>M.integrate(M.parse(s),l,r)));

const presets=JSON.parse(await readFile(new URL('presets.json',base)));
for(const p of presets)test('PAU loadable fragment '+p.id,()=>{assert.ok(E.flatMap(e=>e.questions).some(q=>q.id===p.question));const r=solve(p.tool,p.params);assert.equal(r.tool,p.tool);});
const preset=id=>{const p=presets.find(x=>x.id===id);return solve(p.tool,p.params);};
test('PAU 2024 system reference',()=>{const r=preset('24-parametre');assert.deepEqual(r.special.map(s=>s.kind),['SI','SCI']);r.at.particular.forEach((v,i)=>close(v,[-11,-3,7][i]));});
test('PAU 2024 dotted area reference',()=>close(preset('24-area').integral.value,9));
test('PAU 2024 binomial reference',()=>close(preset('24-binomial').probability,.5904));
test('PAU 2024 Bayes reference',()=>close(preset('24-bayes').posterior[0],.01/.806));
test('PAU 2026 two geometric regions',()=>close(preset('26-pala').integral.value,16));
test('PAU 2026 stationary points',()=>{const r=preset('26-seguidors');assert.equal(r.critical.length,2);close(r.critical[0].x,3);close(r.critical[0].y,1240);close(r.critical[1].x,5);close(r.critical[1].y,1200);});
test('PAU 2026 no continuity correction',()=>{const r=preset('26-binomial');close(r.approx.zr,1.96);close(r.approx.probability,.975,1e-5);});
test('PAU 2026 confidence reference',()=>{const r=preset('26-interval');close(r.lo,2.9351,2e-5);close(r.hi,2.9649,2e-5);});
test('PAU 2026 matrix reference',()=>assert.deepEqual(preset('26-matriu').result,[[1333,533,134]]));
test('PAU 2026 scholarship reference',()=>preset('26-beques').particular.forEach((v,i)=>close(v,[830,103,103][i])));
for(const[c,plan]of Object.entries(P))test('realistic editable budget '+c,()=>{const hours=plan.flat().map(id=>T.find(t=>t.id===id).sessions[c]);assert.ok(hours.every(h=>Number.isInteger(h)&&h>0));assert.ok(hours.reduce((a,b)=>a+b,0)<(c.endsWith('1')?128:112));});
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const appCode=await readFile(new URL('../js/app.mjs',import.meta.url),'utf8');
test('valid option closing tags',()=>{assert.ok(!/<\/option\s/.test(html+appCode));assert.ok(appCode.includes('<option value="2026">2026</option>'));});
test('all course choices available',()=>{for(const c of ['all','sci1','sci2','soc1','soc2'])assert.ok(html.includes('<option value="'+c+'">'));});
console.log(JSON.stringify({suite:'engine-data-generators',passed,failed,failures},null,2));
if(failed)process.exitCode=1;
