from pathlib import Path
import json,re
from playwright.sync_api import sync_playwright
root=Path(__file__).resolve().parents[1]
def bundle(snapshot=None):
 eng=(root/'js/engine.mjs').read_text()
 exports=re.findall(r'export (?:function|const) (\w+)',eng)
 eng=re.sub(r'export (function|const) ',r'\1 ',eng)
 engine='const M=(()=>{'+eng+';return {'+','.join(exports)+'};})();'
 sol=(root/'js/solver.mjs').read_text().replace("import * as M from './engine.mjs';",'').replace('export function solve','function solve')
 gen=(root/'js/generator.mjs').read_text().replace("import * as M from './engine.mjs';",'').replace('export function generateExercise','function generateExercise')
 app=(root/'js/app.mjs').read_text().replace("import * as M from './engine.mjs';",'').replace("import {generateExercise} from './generator.mjs';",'').replace('import.meta.url',"'https://fixture.invalid/js/app.mjs'")
 worker=engine+sol+"\nself.onmessage=({data})=>{try{self.postMessage({id:data.id,result:solve(data.tool,data.params)});}catch(e){self.postMessage({id:data.id,error:e.message});}};"
 maps={f'./data/{s}.json':(root/f'data/{s}.json').read_text() for s in ['topics','exams','plans','presets']}
 setup='''const ORIGINAL_FETCH=window.fetch.bind(window); const DATA='''+json.dumps(maps)+''';window.fetch=async function(url){if(String(url).startsWith('blob:'))return ORIGINAL_FETCH(url);if(DATA[url])return new Response(DATA[url],{status:200,headers:{'Content-Type':'application/json'}});throw Error('External fetch disabled in isolated UI fixture');};
const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(){super(URL.createObjectURL(new Blob(['''+json.dumps(worker)+'''],{type:'text/javascript'})));}};
const memory=new Map(Object.entries('''+json.dumps(snapshot or {})+'''));window.fixtureDownloads=[];HTMLAnchorElement.prototype.click=function(){if(this.download)window.fixtureDownloads.push({name:this.download,url:this.href});};Object.defineProperty(window,'localStorage',{value:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k),clear:()=>memory.clear()}});
'''
 return setup+engine+'\n'+gen+'\n'+app


def start_page(browser, snapshot=None, width=1440):
    import base64
    page=browser.new_page(viewport={"width":width,"height":1000})
    page.set_default_timeout(6000)
    page.errors=[]
    page.on("pageerror",lambda error:page.errors.append(str(error)))
    page.on("dialog",lambda dialog:dialog.accept())
    html=(root/"index.html").read_text()
    html=re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]+>','',html)
    html=re.sub(r'<script[^>]*>.*?</script>','',html)
    html=re.sub(r'<link[^>]+>','',html)
    html=html.replace('./icons/icon-96.png','data:image/png;base64,'+base64.b64encode((root/'icons/icon-96.png').read_bytes()).decode())
    page.set_content(html)
    page.add_style_tag(content=(root/"styles.css").read_text())
    page.add_script_tag(content=bundle(snapshot))
    page.wait_for_function("window.appReady === true")
    return page


def main():
    import os
    from playwright.sync_api import expect
    out=Path(os.environ.get("MATES_QA_DIR",str(root.parent/'mates-qa')))
    out.mkdir(exist_ok=True)
    checks=[]
    def check(condition,name):
        if not condition: raise AssertionError(name)
        checks.append(name)
        print("PASS",name,flush=True)
    def go(page,route):
        page.evaluate("r=>location.hash=r",route)
        page.wait_for_timeout(55)
        page.locator('#main h1').first.wait_for()
    def stored(page):
        return page.evaluate("JSON.parse(localStorage.getItem('mates-batx-docent-v2'))")
    def calc(page):
        page.click('#solve-button')
        page.wait_for_function("!document.querySelector('#solve-button').disabled && !document.querySelector('#lab-output').innerText.includes('Calculant')",timeout=15000)
        return page.locator('#lab-output').inner_text()
    with sync_playwright() as pw:
        exe=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium')
        browser=pw.chromium.launch(executable_path=exe if Path(exe).exists() else None,headless=True,args=['--no-sandbox'])
        page=start_page(browser)
        check(page.locator('.metric').count()==4,'Home metrics render')
        check(page.locator('#course option').count()==5,'All four courses and global option')
        page.screenshot(path=str(out/'inici-escriptori.png'),full_page=True)
        for route in ['topics','exams','comparison','planner','workbook','settings','lab','home']:
            go(page,route)
            check(page.locator('#main h1').count()==1,'Route '+route)
        topics=json.loads((root/'data/topics.json').read_text())
        for t in topics:
            go(page,'topics/'+t['id'])
            check(page.locator('#main h1').inner_text()==t['title'],'Topic '+t['id'])
            check(page.locator('.formula-block').count()>0,'Formulas '+t['id'])
        go(page,'topics')
        check(page.locator('#topic-grid .card').count()==31,'All 31 topics')
        page.fill('#topic-search','deriv')
        check(0<page.locator('#topic-grid .card').count()<31,'Topic search')
        page.fill('#topic-search','INTEGRAL')
        check(page.locator('#topic-grid .card').count()>0,'Case insensitive topic search')
        page.fill('#topic-search','xyznotatopic')
        check(page.locator('#topic-grid .card').count()==0,'Empty topic search')
        go(page,'topics/derivative')
        page.click('[data-action=favorite]')
        page.fill('[data-note=derivative]','Notes de prova: <script>alert(1)</script> i accents.')
        page.select_option('[data-status=derivative]','taught')
        check(stored(page)['notes']['derivative'].startswith('Notes de prova'),'Note saved')
        go(page,'topics')
        page.check('#topic-favorites')
        check(page.locator('#topic-grid .card').count()==1,'Favorite filter')
        go(page,'topics/derivative')
        check('<script>' in page.input_value('[data-note=derivative]'),'Note roundtrip text')
        check(stored(page)['status']['derivative']=='taught','Status saved')
        page.click('[data-action=add-example]')
        go(page,'workbook')
        check(page.locator('.workbook-item').count()==1,'Topic example added to dossier')
        for family in ['quadratic','derivative','integral','system','binomial','bayes','optimization','confidence']:
            page.select_option('#gen-family',family)
            page.fill('#gen-seed','21')
            page.click('[data-action=generate]')
            check(stored(page)['exercises'][-1]['id'].endswith('21'),'Seeded generator '+family)
        page.locator('details').first.locator('summary').click()
        page.fill('#custom-form [name=title]','Prova propia')
        page.fill('#custom-form [name=question]','Text <img src=x onerror=alert(1)>')
        page.fill('#custom-form [name=steps]','Primer pas\nSegon pas')
        page.click('#custom-form button')
        check(page.locator('.workbook-item').count()==10,'Custom exercise added')
        check(page.locator('.workbook-item img').count()==0,'Custom HTML escaped')
        page.locator('[data-action=remove-exercise]').last.click()
        check(page.locator('.workbook-item').count()==9,'Exercise removal confirmed')
        go(page,'exams')
        check(page.locator('#exam-list>section').count()==12,'12 examination records')
        page.select_option('#exam-year','2026')
        check(page.locator('#exam-list>section').count()==4,'Year filter')
        page.select_option('#exam-track','soc')
        check(page.locator('#exam-list>section').count()==2,'Subject filter')
        page.select_option('#exam-session','ord')
        check(page.locator('#exam-list>section').count()==1,'Session filter')
        page.locator('#exam-list summary').click()
        page.locator('[data-action=select-question]').first.click()
        go(page,'workbook')
        check(page.locator('.question-row').count()==1,'PAU reference added to dossier')
        go(page,'comparison')
        check(page.locator('#compare-table tbody tr').count()>10,'Curriculum crosswalk renders')
        page.select_option('#compare-track','soc')
        page.select_option('#compare-level','2')
        check(page.locator('#compare-table tbody tr').count()>5,'Crosswalk filters')
        page.select_option('#course','soc1')
        go(page,'topics')
        check(page.locator('#topic-grid .card').count()<31,'Course topic filter')
        go(page,'planner')
        check(page.locator('[data-hours]').count()>8,'Plan for Socials I')
        first=page.locator('[data-hours]').first.get_attribute('data-hours')
        page.locator('[data-hours]').first.fill('9')
        page.locator('[data-hours]').first.dispatch_event('change')
        check(stored(page)['hours'][first]==9,'Plan sessions persisted')
        order=page.locator('[data-move-topic]').first.get_attribute('data-move-topic')
        page.locator('[data-action=plan-down]').first.click()
        check(page.locator('[data-move-topic]').nth(1).get_attribute('data-move-topic')==order,'Plan reorder')
        page.locator('[data-move-topic]').first.select_option('2')
        check(len(stored(page)['plans']['soc1'][2])>0,'Plan trimester move')
        page.select_option('#course','all')
        tools=['calculus','equation','limit','system','parameters','matrix','bayes','binomial','normal','confidence','statistics','geometry','finance']
        for tool in tools:
            go(page,'lab/'+tool)
            text=calc(page)
            check('Cal revisar les dades' not in text,'Default solver '+tool)
            check(page.locator('[data-action=save-calculation]').count()==1,'Result action '+tool)
        presets=json.loads((root/'data/presets.json').read_text())
        for pre in presets:
            go(page,'lab/'+pre['tool']+'?preset='+pre['id'])
            for k,v in pre['params'].items():
                check(page.input_value('#tool-form [name='+k+']')==str(v),'Preset field '+pre['id']+'/'+k)
            text=calc(page)
            check('Cal revisar les dades' not in text,'Official fragment '+pre['id'])
        go(page,'lab/calculus')
        page.fill('[name=f]','sin(x^2)')
        page.fill('[name=a]','1')
        page.fill('[name=lo]','0')
        page.fill('[name=hi]','1')
        text=calc(page)
        check('Primitiva' in text or 'primitiva' in text,'Unsupported symbolic primitive handled')
        check(page.locator('#plot').count()==1,'Graph still available when primitive unsupported')
        page.fill('[name=f]','alert(1)')
        text=calc(page)
        check('Cal revisar les dades' in text,'Invalid expression rejected')
        page.click('[data-action=tool-defaults]')
        calc(page)
        page.check('#g-d');page.check('#g-dd');page.check('#g-s');page.check('#g-area')
        page.fill('#g-xmin','4');page.fill('#g-xmax','-4')
        check(len(page.locator('#graph-warning').inner_text())>10,'Invalid graph bounds explained')
        page.fill('#g-xmin','-4');page.fill('#g-xmax','4')
        check(page.locator('#graph-warning').inner_text()=='','Graph bounds recover')
        page.click('[data-action=project]')
        check('projection' in page.locator('body').get_attribute('class'),'Projection activates')
        page.keyboard.press('Escape')
        check('projection' not in page.locator('body').get_attribute('class'),'Projection escape')
        page.click('#theme')
        check('dark' in page.locator('body').get_attribute('class'),'Dark theme')
        page.evaluate('scrollTo(0,0)')
        page.screenshot(path=str(out/'laboratori-fosc.png'),full_page=True)
        page.click('#theme')
        page.evaluate('scrollTo(0,0)')
        page.screenshot(path=str(out/'laboratori-escriptori.png'),full_page=True)
        page.click('[data-action=save-calculation]')
        check(len(stored(page)['exercises'])==10,'Calculation stored in dossier')
        go(page,'settings')
        page.click('[data-action=export]')
        # Blob anchor inspected before the app revokes it. No download permission required.
        exported=page.evaluate("async()=>{let d=fixtureDownloads.at(-1);return {name:d.name,data:await(await fetch(d.url)).text()}}")
        check(exported['name'].endswith('.json'),'Export filename')
        backup=json.loads(exported['data'])
        check(backup['notes']['derivative'].startswith('Notes de prova'),'Export contains user data')
        page.locator('#import-file').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':b'{invalid'})
        page.wait_for_timeout(80)
        check(stored(page)['schema']==2,'Invalid import preserves state')
        backup['notes']['derivative']='Restaurat correctament'
        page.locator('#import-file').set_input_files({'name':'backup.json','mimeType':'application/json','buffer':json.dumps(backup).encode()})
        page.wait_for_timeout(100)
        check(stored(page)['notes']['derivative']=='Restaurat correctament','Import roundtrip')
        snap=page.evaluate("({'mates-batx-docent-v2':localStorage.getItem('mates-batx-docent-v2')})")
        page2=start_page(browser,snap)
        go(page2,'topics/derivative')
        check(page2.input_value('[data-note=derivative]')=='Restaurat correctament','Fresh app state hydration')
        page2.close()
        (out/'fixture-backup.json').write_text(json.dumps(backup))
        for w in [320,390,768,1024]:
            page.set_viewport_size({'width':w,'height':900})
            for r in ['home','topics/derivative','lab/calculus','planner','comparison','exams','workbook','settings']:
                go(page,r)
                if r=='lab/calculus':calc(page)
                overflow=page.evaluate('document.documentElement.scrollWidth > innerWidth+1')
                if overflow:
                    offenders=page.evaluate("[...document.querySelectorAll('main *,header *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2).map(e=>({tag:e.tagName,cls:e.className,id:e.id,right:e.getBoundingClientRect().right})).slice(0,15)")
                    raise AssertionError('Overflow '+str(w)+' '+r+' '+json.dumps(offenders))
                check(not overflow,'Responsive '+str(w)+' '+r)
            go(page,'home');page.evaluate('scrollTo(0,0)')
            page.screenshot(path=str(out/('inici-'+str(w)+'.png')),full_page=True)
        page.set_viewport_size({'width':1440,'height':1000})
        go(page,'topics/integral')
        page.emulate_media(media='print')
        page.evaluate("dispatchEvent(new Event('beforeprint'))")
        check(not page.locator('#sidebar').is_visible(),'Print hides navigation')
        check(page.locator('main details:not([open])').count()==0,'Print expands solutions')
        page.screenshot(path=str(out/'impressio-integrals.png'),full_page=True)
        page.emulate_media(media='screen')
        page.evaluate("dispatchEvent(new Event('afterprint'))")
        check(not page.errors,'No browser runtime errors: '+str(page.errors))
        result={'passed':len(checks),'failed':0,'checks':checks,'browser_errors':page.errors,'method':'Real Chromium rendering and Blob Worker; fixture replaces fetch/localStorage on about:blank because navigation is blocked by managed browser policy. Does not test real installation, real localStorage durability or real service worker lifecycle.'}
        (out/'ui-results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
        print(json.dumps({'passed':len(checks),'failed':0,'screenshots':str(out)}))
        browser.close()

if __name__=='__main__':
    main()
